import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MarryMyHusband } from "../../../../assets"
export const Episodes = [
    {
        id: 1,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/15S6GZgzweEiVPo6NZtddNQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1q0o4pMPSyMg9zJR54cX57g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1grLeH83JWC_7fqwk4ERHrw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1BaJqQ0jGaYS5wace9fmpOg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1RuEaCaIbG-GUlYYN-pmGMw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/19gf10kazpY1dyrFrnaD8fw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1lemiujAO0Kizh-VOS9HhqA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZQcF7JujqqBjc7_VoXelUQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/134hlsHxIIPN8FepqebldNA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1a1M7xcSqK6AEdS179SjITw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1Z9xEYlZBeAQ0avWN58Nx0A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1CzmqMA7VGzx72pvxzUcBsw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1wDvkkv3vAtZrfpuBZv2v9A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1u61IP9RqSvnfKRZU8GQt3Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/14Sljomm_r123bP1JrfDleg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: verificationCode[14].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1OoWaRyuI9PceXmWKxj4Wzw',
        youtubeLink: '',
        uploaded: true,
    },
]
