import { MarryMyHusband } from "../../../../assets"
export const Episodes = [
    {
        id: 1,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: 'https://youtu.be/ppgFkzQ10ow?si=Jofn2FQiGjkCtjbd',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Marry My Husband',
        imageUrl: MarryMyHusband,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]
