import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import {TheWheelOfTimeS2 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1A5UF-N4ypawB4Wx6o_pX2Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1o98PmMTW641H048vpJNGAw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1OijSviJiSK4LkFmWGNWZpg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1-zbUjVBd0qLXaFq6crkWPQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1n54NQumPVg25B5qhXkzEaA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1vnULdxlXrRKpBhcHCWT0Cg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1kjHv7d7pcBYHLYaif7lMig',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1-A3OcaO92d2xrEs7zw_zMQ',
        youtubeLink: '',
        uploaded: false,
    },
]