import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import {TheWheelOfTimeS2 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'The Wheel Of Time Season 1',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[44].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]