import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { TheLegendOfTheBlueSea } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/100s3Ri713jftCAnkGJjytg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1SZxttpQYmp2Blr2AR9_TVg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1CsSnkeb62i8NeHxf4sv6mA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1PAhB87WO6lMyTlFqeltipQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1HGS1n16iM9c1ZCRddpIFEA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/19eANfNy437T_5OeXYrQGqg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1wPl3Q7CBRD5XfJPwZdG3xg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1IPESZn--lc0CEpfcA0vBqg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1iPn6tpDPjLiv0apbpN7HUg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/17Jsjwsn5wC8s7uBBx_ceJA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1IHe6NRhwScHUbI2SMEH2Ig',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1i7uuiIAWM3NiOfHbHqfvqA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1vCMfPaVosQTradPATWAuWQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/199qCi92MPl8H2yV1lz5v5Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1Tt7rleU5eeUb_IdclES3ig',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/15KuqIpvRwfhITgMMCx3umA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1lmlB0X8wvaCIvd78Jw4Fiw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1kexJPoJ3M656K_f5eWbesw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1uHnyo_T97HUIoInQsEGHXw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1BmIXkLomqdn5dkpVwpgr2Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1mJLK56sIi6NQZz8nuoFwsw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1h4ccuU71SD3j-zsGx514DQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1SvxiPpHoyPhBCHGdfnzXeg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/181jmqen1s4JU1NtbWMN5pg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/16WTs8hgbm1X_zQqXr1OUIg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1pwz8S6CJRqQObYWLQaMdvw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/16Zj6iGCA033WQWHIuggbEw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1lU4nWKsc08kvoRuIEPILvQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 29,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1kPgz0EpU94B6qV0tN_F5zA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 30,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1irV4SqP5NhpwDoEKgz5eXQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 31,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[30].verificationCode,
        videolink: 'https://1024terabox.com/s/1RP0_qkYgSErYzVKYaV4CCw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 32,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[31].verificationCode,
        videolink: 'https://1024terabox.com/s/1nVrnj2bjQm8EChv6_0Yn6g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 33,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[32].verificationCode,
        videolink: 'https://1024terabox.com/s/1gfBp7NvLeZUKtgvReKrTog',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 34,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[33].verificationCode,
        videolink: 'https://1024terabox.com/s/19tcadqSHJHcsOexj0qBrMQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 35,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[34].verificationCode,
        videolink: 'https://1024terabox.com/s/1Fm1aiTTsUp9x4h1pCsMsTQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 36,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[35].verificationCode,
        videolink: 'https://1024terabox.com/s/1oSmScXwcq065mgG58j2PsA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 37,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[36].verificationCode,
        videolink: 'https://1024terabox.com/s/1RXQTTeMueFEGR0rI4qarLw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 38,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[37].verificationCode,
        videolink: 'https://1024terabox.com/s/1WhK304VLedRQbjpQHL1D5A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 39,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[38].verificationCode,
        videolink: 'https://1024terabox.com/s/14bWGODKoUCPAra1lZv-GCw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 40,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: verificationCode[22].episodes[39].verificationCode,
        videolink: 'https://1024terabox.com/s/1GZgSpnz878CIF6hhd-hGRA',
        youtubeLink: '',
        uploaded: true,
    },
]