import { TheLegendOfTheBlueSea } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 33,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 34,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 35,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 36,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 37,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 38,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 39,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 40,
        title: 'The Legend Of The Blue Sea',
        imageUrl: TheLegendOfTheBlueSea,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]