import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { theSecretLifeOfMySecretry } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id:12,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'The Secret Life Of My Secretry',
        imageUrl: theSecretLifeOfMySecretry,
        verificationCode: verificationCode[79].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]