export const verificationCode = [

    {
        id: 1,
        dramaName: 'Descendants Of The Sun',
        status:'free',
        episodes: [
            { id: 1, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP241724' },
            { id: 2, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP242724' },
            { id: 3, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP243724' },
            { id: 4, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP244724' },
            { id: 5, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP245724' },
            { id: 6, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP246724' },
            { id: 7, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP247724' },
            { id: 8, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP248724' },
            { id: 9, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP249724' },
            { id: 10, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP2417240' },
            { id: 11, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP2417241' },
            { id: 12, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP2417242' },
            { id: 13, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP2417243' },
            { id: 14, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP2417244' },
            { id: 15, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP2417245' },
            { id: 16, title: 'Descendants Of The Sun', verificationCode: 'DOTSUNEP2417246' },
        ]
    },
    {
        id: 2,
        dramaName: 'Love Is Sweet',
        status:'free',
        episodes: [
            { id: 1, title: 'Love Is Sweet', verificationCode: 'LIS2407241',},
            { id: 2, title: 'Love Is Sweet', verificationCode: 'LIS2407242',},
            { id: 3, title: 'Love Is Sweet', verificationCode: 'LIS2407243',},
            { id: 4, title: 'Love Is Sweet', verificationCode: 'LIS2407244',},
            { id: 5, title: 'Love Is Sweet', verificationCode: 'LIS2407245',},
            { id: 6, title: 'Love Is Sweet', verificationCode: 'LIS2407246',},
            { id: 7, title: 'Love Is Sweet', verificationCode: 'LIS2407247',},
            { id: 8, title: 'Love Is Sweet', verificationCode: 'LIS2407248',},
            { id: 9, title: 'Love Is Sweet', verificationCode: 'LIS2407249',},
            { id: 10, title: 'Love Is Sweet', verificationCode: 'LIS24072410',},
            { id: 11, title: 'Love Is Sweet', verificationCode: 'LIS24072411',},
            { id: 12, title: 'Love Is Sweet', verificationCode: 'LIS24072412',},
            { id: 13, title: 'Love Is Sweet', verificationCode: 'LIS24072413',},
            { id: 14, title: 'Love Is Sweet', verificationCode: 'LIS24072414',},
            { id: 15, title: 'Love Is Sweet', verificationCode: 'LIS24072415',},
            { id: 16, title: 'Love Is Sweet', verificationCode: 'LIS24072416',},
            { id: 17, title: 'Love Is Sweet', verificationCode: 'LIS24072417',},
            { id: 18, title: 'Love Is Sweet', verificationCode: 'LIS24072418',},
            { id: 19, title: 'Love Is Sweet', verificationCode: 'LIS24072419',},
            { id: 20, title: 'Love Is Sweet', verificationCode: 'LIS24072420',},
            { id: 21, title: 'Love Is Sweet', verificationCode: 'LIS24072421',},
            { id: 22, title: 'Love Is Sweet', verificationCode: 'LIS24072422',},
            { id: 23, title: 'Love Is Sweet', verificationCode: 'LIS24072423',},
            { id: 24, title: 'Love Is Sweet', verificationCode: 'LIS24072424',},
            { id: 25, title: 'Love Is Sweet', verificationCode: 'LIS24072425',},
            { id: 26, title: 'Love Is Sweet', verificationCode: 'LIS24072426',},
            { id: 27, title: 'Love Is Sweet', verificationCode: 'LIS24072427',},
            { id: 28, title: 'Love Is Sweet', verificationCode: 'LIS24072428',},
            { id: 29, title: 'Love Is Sweet', verificationCode: 'LIS24072429',},
            { id: 30, title: 'Love Is Sweet', verificationCode: 'LIS24072430',},
            { id: 31, title: 'Love Is Sweet', verificationCode: 'LIS24072431',},
            { id: 32, title: 'Love Is Sweet', verificationCode: 'LIS24072432',},
            { id: 33, title: 'Love Is Sweet', verificationCode: 'LIS24072433',},
            { id: 34, title: 'Love Is Sweet', verificationCode: 'LIS24072434',},
            { id: 35, title: 'Love Is Sweet', verificationCode: 'LIS24072435',},
            { id: 36, title: 'Love Is Sweet', verificationCode: 'LIS24072436',},
        ]
    },
    {
        id: 3,
        dramaName: 'W Two Worlds Apart',
        status:'free',
        episodes: [
            { id: 1, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24701' },
            { id: 2, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24702' },
            { id: 3, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24703' },
            { id: 4, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24704' },
            { id: 5, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24705' },
            { id: 6, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24706' },
            { id: 7, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24707' },
            { id: 8, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24708' },
            { id: 9, title: 'W Two Worlds Apart', verificationCode: 'WTWEP24709' },
            { id: 10, title: 'W Two Worlds Apart', verificationCode: 'WTWEP247010' },
            { id: 11, title: 'W Two Worlds Apart', verificationCode: 'WTWEP247011' },
            { id: 12, title: 'W Two Worlds Apart', verificationCode: 'WTWEP247012' },
            { id: 13, title: 'W Two Worlds Apart', verificationCode: 'WTWEP247013' },
            { id: 14, title: 'W Two Worlds Apart', verificationCode: 'WTWEP247014' },
            { id: 15, title: 'W Two Worlds Apart', verificationCode: 'WTWEP247015' },
            { id: 16, title: 'W Two Worlds Apart', verificationCode: 'WTWEP247016' },
        ]
    },
    {
        id: 4,
        dramaName: 'Dine With Love',
        status:'free',
        episodes: [
            { id: 1, title: 'Dine With Love', verificationCode: 'DWL2507241' },
            { id: 2, title: 'Dine With Love', verificationCode: 'DWL2507242' },
            { id: 3, title: 'Dine With Love', verificationCode: 'DWL2507243' },
            { id: 4, title: 'Dine With Love', verificationCode: 'DWL2507244' },
            { id: 5, title: 'Dine With Love', verificationCode: 'DWL2507245' },
            { id: 6, title: 'Dine With Love', verificationCode: 'DWL2507246' },
            { id: 7, title: 'Dine With Love', verificationCode: 'DWL2507247' },
            { id: 8, title: 'Dine With Love', verificationCode: 'DWL2507248' },
            { id: 9, title: 'Dine With Love', verificationCode: 'DWL2507249' },
            { id: 10, title: 'Dine With Love', verificationCode: 'DWL25072410' },
            { id: 11, title: 'Dine With Love', verificationCode: 'DWL25072411' },
            { id: 12, title: 'Dine With Love', verificationCode: 'DWL25072412' },
            { id: 13, title: 'Dine With Love', verificationCode: 'DWL25072413' },
            { id: 14, title: 'Dine With Love', verificationCode: 'DWL25072414' },
            { id: 15, title: 'Dine With Love', verificationCode: 'DWL25072415' },
            { id: 16, title: 'Dine With Love', verificationCode: 'DWL25072416' },
        ],
    },
    {
        id: 5,
        dramaName: 'Encounter',
        status:'free',
        episodes: [
            { id: 1, title: 'Encounter', verificationCode: 'ENC72401' },
            { id: 2, title: 'Encounter', verificationCode: 'ENC72402' },
            { id: 3, title: 'Encounter', verificationCode: 'ENC72403' },
            { id: 4, title: 'Encounter', verificationCode: 'ENC72404' },
            { id: 5, title: 'Encounter', verificationCode: 'ENC72405' },
            { id: 6, title: 'Encounter', verificationCode: 'ENC72406' },
            { id: 7, title: 'Encounter', verificationCode: 'ENC72407' },
            { id: 8, title: 'Encounter', verificationCode: 'ENC72408' },
            { id: 9, title: 'Encounter', verificationCode: 'ENC72409' },
            { id: 10, title: 'Encounter', verificationCode: 'ENC724010' },
            { id: 11, title: 'Encounter', verificationCode: 'ENC724011' },
            { id: 12, title: 'Encounter', verificationCode: 'ENC724012' },
            { id: 13, title: 'Encounter', verificationCode: 'ENC724013' },
            { id: 14, title: 'Encounter', verificationCode: 'ENC724014' },
            { id: 15, title: 'Encounter', verificationCode: 'ENC724015' },
            { id: 16, title: 'Encounter', verificationCode: 'ENC724015' },
        ],
    },
    {
        id: 6,
        dramaName: 'Business Proposal',
        status:'free',
        episodes: [
            { id: 1, title: 'Business Proposal', verificationCode: 'BP2407251' },
            { id: 2, title: 'Business Proposal', verificationCode: 'BP2407252' },
            { id: 3, title: 'Business Proposal', verificationCode: 'BP2407253' },
            { id: 4, title: 'Business Proposal', verificationCode: 'BP2407254' },
            { id: 5, title: 'Business Proposal', verificationCode: 'BP2407255' },
            { id: 6, title: 'Business Proposal', verificationCode: 'BP2407256' },
            { id: 7, title: 'Business Proposal', verificationCode: 'BP2407257' },
            { id: 8, title: 'Business Proposal', verificationCode: 'BP2407258' },
            { id: 9, title: 'Business Proposal', verificationCode: 'BP2407259' },
            { id: 10, title: 'Business Proposal', verificationCode: 'BP24072510' },
            { id: 11, title: 'Business Proposal', verificationCode: 'BP24072511' },
            { id: 12, title: 'Business Proposal', verificationCode: 'BP24072512' },
        ],
    },
    {
        id: 7,
        dramaName: 'Extra Ordinary You',
        status:'free',
        episodes: [
            { id: 1, title: 'Extra Ordinary You', verificationCode: 'EOY2507241' },
            { id: 2, title: 'Extra Ordinary You', verificationCode: 'EOY2507242' },
            { id: 3, title: 'Extra Ordinary You', verificationCode: 'EOY2507243' },
            { id: 4, title: 'Extra Ordinary You', verificationCode: 'EOY2507244' },
            { id: 5, title: 'Extra Ordinary You', verificationCode: 'EOY2507245' },
            { id: 6, title: 'Extra Ordinary You', verificationCode: 'EOY2507246' },
            { id: 7, title: 'Extra Ordinary You', verificationCode: 'EOY2507247' },
            { id: 8, title: 'Extra Ordinary You', verificationCode: 'EOY2507248' },
            { id: 9, title: 'Extra Ordinary You', verificationCode: 'EOY2507249' },
            { id: 10, title: 'Extra Ordinary You', verificationCode: 'EOY25072410' },
            { id: 11, title: 'Extra Ordinary You', verificationCode: 'EOY25072411' },
            { id: 12, title: 'Extra Ordinary You', verificationCode: 'EOY25072412' },
            { id: 13, title: 'Extra Ordinary You', verificationCode: 'EOY25072413' },
            { id: 14, title: 'Extra Ordinary You', verificationCode: 'EOY25072414' },
            { id: 15, title: 'Extra Ordinary You', verificationCode: 'EOY25072415' },
            { id: 16, title: 'Extra Ordinary You', verificationCode: 'EOY25072416' },
        ],
    },
]
