import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { StartUp } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1aGBLO3_gEl8plA71I4NVdQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1pIve6weAti6nnBwb3YQWFA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1RIYRtLRf8VuAsvVXpwt4Zw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1pCW92lv4K-Iyy_ZLwVIHFw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1TqszNMlditAxni9R-pZOiQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1sqDLLHczfwzLpxjRGkGdKg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/17_qZj4Alh-NZMxtb2UuHTA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1Z3_TXNmTDLW2SZKthECDbg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1oy8-1LwEQqxxnvhQjrYTtw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1qtV5FHREk7K6Ve16NGGKnA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1dj3M3modA49fbUWX2b3CXQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1qkulAbURkrcyjx1wIZjIbw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1H1GXVqd-Z7UZBlorWT80vA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1Cl6dLcKi6VD36ycquVx1Hg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1Eywh-XXuZFlpBtfZFZ7B-g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'StartUp',
        imageUrl: StartUp,
        verificationCode: verificationCode[40].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/16by6urkhDBjkOh4o5nJSUw',
        youtubeLink: '',
        uploaded: true,
    },
]