import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { SnowDrop } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1-aA1n8D-8EkupxWB4EOVJQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1_pn0SgzBeYrvbBd_Pn2Xxg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1VSF4NSKeLCajeZaF44cP7g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1lAscBsbKCqOPPCVYHx3E0w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1arlm1tEGe0siMxJQyBLbdA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1reVIN2PWsVS8tu-LReJ9Fw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/13J95kOVtqKDRdXga4wMxAg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1QD32ibbIrvS6hnN1dphsqg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/10EFkvtjLUQDR9B6axRfsbQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1M5or1rqO298HHnKskSGt2Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/10orEoNu1p3mDBrSSU_kCDg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/18-8z1EoA2xXISyOX0mUiAQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1cNBUt4Vh9Z08uhzFmAnzIQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1FnZaNdPEcweuPG2j0TR1RQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1uZO2_0Q-ZXBsrC5_w1SyeQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Snow Drop',
        imageUrl: SnowDrop,
        verificationCode: verificationCode[24].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1PmLyrigQtkmJg6oTHPzKtw',
        youtubeLink: '',
        uploaded: true,
    },
]