import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { QueenOfTears } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1Lcy5WkdcIKaBaTpnQV6aoQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1zdpBKwNSzCUES6nUDHwxLA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1NEJJxyTSec7HnxMrY3t4jg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1LcYiEv6qncGjMfetZTbfEg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/140sV4XDWI_f-tFzv2seBCA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1VE2YMrdSYIxCsOSu9Fp-yw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1dg5uKOTslK0bT3QSmeBrnA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1XxFJHb67kNw3RxKx3ooAYA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1i5f95NVc1cJJ2lJxZvSU9A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1zQz94ozpqfUuFtyUVNsIRw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1f5n0nkzGotiNVqCruzpxKg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1w5DOsg4HKef8yq5XceDZeA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1FjzX0KRFAwY4-PUF-ZA0nA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/11z7u_rGL5tlm4saByN8Flw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1uj-xIeM0bmcnjSagJvlqSQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Queen Of Tears',
        imageUrl: QueenOfTears,
        verificationCode: verificationCode[20].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1fKFXCWYFD4T9va2ZRjUv5g',
        youtubeLink: '',
        uploaded: true,
    },
]