import { CuteBodyGaurd } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1uxLAnNuCd6qqBIep6uKScw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]