import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { CuteBodyGaurd } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/11kcKpbY1U0X_24OXEnS_zw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1bDxwaksKeqGnq5L8rbas9w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1iISYvD_go62SttZnMwZi1Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1-oDU1-0RToE-xNnGwsi53w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1g7nriB2ce7Wb6YqBPwF8Ug',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1o-l3vK8R4w6LexmNYatdvg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1n6HSprUfxtwBWamMG9yBcA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1xMfFtlHnm1Cgzg40HNfNbQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1Uk9cMB8_Zhg3RH6Es5Fy7g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1IXZkV2JNxhtfXwWlONqyRA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/10aCCWzC_WZ7vjXUsjzSZow',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1FREV__WFs7Fg0yexATeVUQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1fSMD27dcovqcs7VwJ-w8pA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1XJU9Y2ZzUX-GfxN7ZWfgdg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1BJoPFFBIhKXlyhdzVsrNgg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/15kEftsyZcC9w5iGC4DXq6A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1XZCPoRI9iCNicC7IR1nw-w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1rpoqWvQ0eM84xIXwIU7OXw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1Afy3F0Yar21vKAY93LuzcQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/19jPbXq-OKxK6m8XjlNB7Eg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1uSNQSBs_Y66uM2h64TCAKQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1e5qwzMxNeEYdKoSOM3VUwQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1nbEtMH2Tr1tSj6uIbDP4Ig',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Cute Body Gaurd',
        imageUrl: CuteBodyGaurd,
        verificationCode: verificationCode[7].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1SWy9iB81YpLCV_7nN1UCIQ',
        youtubeLink: '',
        uploaded: true,
    },
]