import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { IntenseLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1y4gDZmPvnK39UPVoFZJ3Sw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1FQ7Q1zRLCQOK_eUAk59kUw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1HNw0UMRPcEu2on37bPkaIQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1gNWwSj5iZk-PqaNnXzUZKQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1pButNxGrkPjBNI3XZvIBqA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1RuVf2-Zc78RULNu1Xulnjg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/11PkjIZdqXjNX4L0pWpsVVQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1XRcWLcJ1TML-T3S488Polw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1tNTI2qN6HyRpCQ38oPoEFw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1QfwkDiaiwRgx3vxCb4JaJQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1-xzfaFDUcEEKWewjaSpUdQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1O7hpibH3D6fNmD-5kDwM6w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1jKdjl0Jmm9rKTK6GW7OnBw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1vKpPB0YbtLt3d28Nfz-mIw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1kZnxLBVzaApA3EuZKMOklw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1OXcO2zmiMRgkl2yafigUQw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/14sZVAh5gcqV9jnfv3YJvdw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1FTqC9VjBEOjh7LlQlvo9sA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1R8ZwvAtPrbqyGT4zrxTkIw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1IshPE0rCQHVSYjx-3FNh0w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1dUYyWj_swn0sqyaSr24t3g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1AdCAgEd-65z_MwulVQu_vg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1gZj8lZkI_XgOfDpR7taCwQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Intense Love',
        imageUrl: IntenseLove,
        verificationCode: verificationCode[62].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1cpWv7k2ptMQSm27IPH78Yw',
        youtubeLink: '',
        uploaded: false,
    },
]