import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MrInsomiaWaitingForLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1Y-kXSY5E4wejrMc7ge15Kg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1byoAcr2xHV_nYaYSHBrq5Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1eH-03rFbdvFnBlxpEVPu3Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1PjADNusJf0w9z9icgltZTA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1r1ReQfqgrizDM0HrRIwBFw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1cGzVLJS5-krpkNHonetMsA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1QYuMdlTtMjIhfEpkEZn0Xg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1XDGJtaiwm08-qAZV8Ee5aw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1iISpuZEu5giAy6b9auD6bg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1Slo8Rpbiw38RaiJeqy_YAg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/16IBn21dt0bcNFm8BpwFp_g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1R_YnzW3VFTNJHonsvDCdrw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1AmR8uXIukVBXzh13NF3uKw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1D8ZlRqCpYGt46h0FYIUz7A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1gAR7r6FAnGzAI2IOMizt0A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1d81i9NAoD7OEV5o5XvVq1g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/18EidH00AzQCOuF51N29Kqg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1GVPiV_3QNWMVounQsd3mtQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1E7TMAroZasGTH93L1lJO2Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1k3qBnA4Ie5p1xuhLhQb9VA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1AEygNnJtqQU1zx9MoGa6Mg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1Cz4CCFFWbn9JrttMbfP6FA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1ktLjkMIo-3uWz60yGDD6Sw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Mr Insomia Waiting For Love',
        imageUrl: MrInsomiaWaitingForLove,
        verificationCode: verificationCode[66].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1A7lwwRLpLWVpYAHuEJlBmA',
        youtubeLink: '',
        uploaded: false,
    },
]