import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyLethalMan } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1yBc9shUyoUpfBOhjiBFuyw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1iNbRk20Pl8aAUbfuXDMeeg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1JLjJQPots-CWp3mmxNksbA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1_02LrNhZ8JuMWA-8c9g6kg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1DPKM0j3VpBaK8UxZSMJF0Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1WebJYtCbtHBEvM68F1-s7g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1mNi0tGLEjlkmBNRPcGxb2Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/110UNUzM0iBjuwThHIHR7mw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1SCSa-VamrfyGyjimbu1HNQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1uMJqITmvBq56zTE3CD3ORg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1dKNbLyx18yWN-hEH0tHrow',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1uREVL7twSWzGFfl-CAL-sw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1Br1suanCHDnwSIFwMu4SLg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1a8LW7UqNDngXwj8ftI38GQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1OyCqTBD18TclbGANQLpiHA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1-5q1bwIAxnzIn5_CnhiPPQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/15UsO8F4Ouy1VfZ_Cgi6fwQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1JUsENIfXE2yIZuKFDCC17Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1kFkXu7zPafpculwA-EOtCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1pjfaJN46CAVzTv8vGPyGLw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1xCLGT5LnkGw0yzs6Pb6mDA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1DyyfL0PQrjhJUnlATSB3Wg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1b2a_7GHnertT2q-6H8Sd6w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'My Lethal Man',
        imageUrl: MyLethalMan,
        verificationCode: verificationCode[71].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1NpJlb3ufzcw7vn0wgxMbBw',
        youtubeLink: '',
        uploaded: false,
    },
]