import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { ExtraOrdinaryYou } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1C2dOWdL0dw2NBgRCThJG-Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/17-r83uQF2i0Csq5hX4Q23g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1Z9paiJU4_zWgQEp5X-J_Ig',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1-RrVh-3MhzeRlb7q79qR3A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1-fZYc24GH05v_NXh_r6gJQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1UyH0zYWU9oC98niIoKuiEA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1cZHzwPOaBDqK70lUetqJ-A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1xom-pTr0UfAaYCNpOkVHLg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1hWPJ8af44n7mb0YUtznAxg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1FtnXKJ_nRhlKv62ozfaBgQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1bWW7dN5F-Bn4qNuB4dCokQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1bcuetW8oJcSMdHJ9rYqzRQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1VLsvDYP8yq3xteLUCwseBA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1D4giSIOlf7SHQA49zCmL9Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1eM-BQMRrO9szFKOKnUAPZw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: verificationCode[6].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1b0KiUSVQNgj55AiBzAIVRQ',
        youtubeLink: '',
        uploaded: true,
    },
]