import { ExtraOrdinaryYou } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1ETjJu1vwUla7l8My9x-8PQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/17-r83uQF2i0Csq5hX4Q23g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1Z9paiJU4_zWgQEp5X-J_Ig',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1-RrVh-3MhzeRlb7q79qR3A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1-fZYc24GH05v_NXh_r6gJQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1UyH0zYWU9oC98niIoKuiEA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Extra Ordinary You',
        imageUrl: ExtraOrdinaryYou,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]