import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyPrecious } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 88,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 88,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[24].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[25].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[26].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[27].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 29,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[28].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 30,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[29].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 31,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[30].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 32,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[31].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 33,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[32].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 34,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[33].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 35,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[34].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 36,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[35].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 37,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[36].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 38,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[37].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 39,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[38].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 40,
        title: 'My Precious',
        imageUrl: MyPrecious,
        verificationCode: verificationCode[88].episodes[39].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
]