import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { LoveScenery } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1Z-bUo7DCLHVt7DlQBt-WCw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1df-JjUX5EyVPjem9a-p2gw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1A12JzSX-MK1weGcB-mllLg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1oB6-aw3FLWU62NlWQlyoeg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1kn0g14RbZDSnSHq_Y1msZA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/11i9jv5HUEHRFEVtRo_XZ2g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/114WJ6VjqnX3W5IGJt0sML1g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1QEtfAb0fmiHe4Bd9mf_1wg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1Gap1ZFmA7BzZGF3-w0fYyg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1yYOJ_wEJIHpxwACrqLRe7A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1Pr_vAj142NdrMBonNNjNq9A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1j_SkU1RQKpjQ33146TJ0ZNA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1-_4n7a-tIdBk0LP4rlkpOA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1_A114qUN5NjdbdA-Ru_TdIA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1NEbLsCnRZ1PCueOI4uO31w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/141hXfql5q0JayPGekC10Bw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1RNh9JUVHB0fevtgD14PJBfA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 114,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1e1Nb30XWjoCNRZOUz_whBg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1AvGPnJm13Un0EfvaS-c3Gg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1qtEmSlLpRpWaNfzzrVp_ug',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1ohp6SRcRPxJXbhrpMwVJ_A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/16oiHb3T2_LL72jh5gBqzXQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1FjxYTgz21sIITTEm5YpWBg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1BzHxjmAbkWNYxq3O1laeXw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1Z4OeOEDFMrFFA6YJhvaZrg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1SFhFJBddr__JSnAOqIvmFw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1RCj5f4dJoZ5Mz0T5WL7eqg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 214,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1yTODub4sUlMQMGKNJaN5IQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 29,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1Dirx414Oal14Zbj1emsdizew',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 30,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1w1VdZ_wiOQGYuYGeyF6fDg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 31,
        title: 'Love Scenery',
        imageUrl: LoveScenery,
        verificationCode: verificationCode[13].episodes[30].verificationCode,
        videolink: 'https://1024terabox.com/s/1vFPht1wIrRpgHdgLCYfAoA',
        youtubeLink: '',
        uploaded: true,
    },
]