import { LoveScenery } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/1brjv8_fg8wRcmUCb2LvPfQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1TH-kcQnMA1QadOBaCr7rtg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1DVHALfoRPYGn3jq7eQ_04w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/14BMKpRXJNodMb4TXbOQo4Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1PjZuPu98r7iqoAiCzl6wRA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/1Zda8Z9cMHKxFYHNaydA0rQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1-pph4FYMfMBvExWfAlAVRw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1e-qBQHmauI3jRQcPPa6Tgg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1zQV-yEf4pNUlt8lAkgvP-Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1rU1DwnTzMqTHUbplkuCuzw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/1duW_XfJ58RIwcx0Ha20J_Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1FY0gg4eDUQ9XCsH72Vl_wQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/18kx8nuO6KSrnqiMI59FXUQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1gaIuZxAysLr3TGu6qp9cwg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1Ke--p1zQ2aMoqnw4LGCicQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/1BN07dgeUXiXKdzqmEB1bgQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1yy9apNmIcSblpm6sAB-1CA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1Tl9wzzFUVISoklCFEMTBCA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1IJR-jRSm9oCZHbZX9SbluQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1eWfIg0AWbDJNseOEx7aYOA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/1ivDfyvP1gH4k4AnNjeiREQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1a1icKtZKMaiQzNniAjUG8A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1fehW9_t2HxEbVdMxKRzuZw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1gEjOwjyiz60JNkKJLpnuQA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1fDXpLHg5ha1Vu8WQnHOBTQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/14lPqqEvBks4AAL8Z-jGSXg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1BHXe8UhLFjxnCs3_WpD0JQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1zk4Ik7Bw9fuiUbDYbZtfHg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1UR97TYScbWErxIp6Xsli4Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/16g_CGRYs0-07S8anJNUXCA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'LoveScenery',
        imageUrl: LoveScenery,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/1VXo19yuamfRvMW_lWEXZOQ',
        youtubeLink: '',
        uploaded: false,
    },
]