import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { SweetAndSaltyOffice } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Sweet And Salty Office',
        imageUrl: SweetAndSaltyOffice,
        verificationCode: verificationCode[76].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]