import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { WenderallasDiary } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Wenderallas Diary',
        imageUrl: WenderallasDiary,
        verificationCode: verificationCode[86].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]