import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyDearLady } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1c3sULEAIIn8Dhz5SWmZZVA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1KE8SVWXFj6FjtMnyoJaOZw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1eEWVf2FbnVBd_bVgrdBEqA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/188h2F38PFbwZ9xMK0MLPTA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1wxtsIwsXsFy-SyQHdFxOQQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1Kw9f0pg8jfSOxodo1vMn6w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1RzaMydaJzzUr-nkgTiw58w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1hXkuDgk7y-ENgh2OHlMghA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/19X6Nt58HEJENjy3ALZNkAw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/136DOnFqhqN-zD6OF9IMINg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1DRgfiDGaGAs6Pjbdn2KziQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1DQm2NlUnDqiDYhyr0L1vIQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1rbmKTtchTabUR-5WILKNEA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/13Bbjf7bRvvTN5hTh3pO4cA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/16XzhrXe5aZXMD5uLNd4Jlg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1tdK9DVCQixDC4YDb08VcKA',
        youtubeLink: '',
        uploaded: false,
    },
]