import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyDearLady } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'My Dear Lady',
        imageUrl: MyDearLady,
        verificationCode: verificationCode[67].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]