import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { CrashLandingOnYou } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1BTdo25ZLuRi86GnbLl-53w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[4].verificationCode,
        videolink: 'Ug',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[8].verificationCode,
        videolink: 'g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[10].verificationCode,
        videolink: 'w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[11].verificationCode,
        videolink: 'Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[12].verificationCode,
        videolink: 'pA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[13].verificationCode,
        videolink: 'g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]