import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { CrashLandingOnYou } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1BTdo25ZLuRi86GnbLl-53w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1b7VjJhWIv0m1yPWCL-YSzA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1jjgwG0rlvoNMuLsufj9MAQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/16-s4aEtOitAROg1R3NnlKw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/16-OyCXR3_4JyZCXHd0cRfQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1Duwa7f6QVJe292CY0aHq8g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/13CzdU-p6Dbv420_dkDXaTQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1yJsKbGf1wP5dkZlTlZAOwA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1KOSjUxbP79cpmR44rdSPHw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1zNTfXmrpL55JrxPggEbZcQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1Dt3olY7mFj6Rl05nJ4Vkkw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1mFA8jl0YGFqTP2rcyZ7mFg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1dw1Bfi9DP332mvQe-Ztjgw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1bo3ksxtr6QMnN_4jAO4z0Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1eh_Pc67pO698FuP2BNP_Kg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Crash Landing On You',
        imageUrl: CrashLandingOnYou,
        verificationCode: verificationCode[27].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZzlAAm7QODkqUEMPv7GvUQ',
        youtubeLink: '',
        uploaded: true,
    },
]