import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { ALoveSoRomantic } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1utQASClOlvRg3hSUZUCOfg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/10giFxsMGlmNGCeO_GVYdpg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1h-v50TmE9TtoKsoBhgdRqA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1cOnXymxH50WKOj-99fLn4w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1K7cg81sh9ph7jQN_6-ucEw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZhiEtU3_vRUu4R-MN5w9Iw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1GGZuvp-gpR5N9_Zs04GlLw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1WjjfdHzU6cDorWDlw1FozQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1iBdi_wSJKlblw5oCJJl7mg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1MIpNkdysb10OFtV-QD8irw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1exjF9eELOzMvgxUU83oVNA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/12E-bkRWgWXy90FYiE9bxCw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1oShr59s0yFtCQ8XV7ZVZBA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1ORyPOdNPxThljUxrgRvDpQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1UzkDw56XcGrviFMqH1vk-g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1igvgU0v6ABj9XO0zp87_mQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ny4e4QCo-1KEVcmBI2aNmA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1kbGzmFZvDmKfIQYSPt5PrQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1rbSFaIK5GnagPvf5LaShbw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1IRsaEZrucqhaSl3VWRkY2w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1buTysYXeCt_PXX5fq0DfzA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1Qo0eeCj68MH0WqTTgGmSxQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1fWB8O_oMrqqNg94TZJmMHA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1ehNLbp-a8zapMBUY0lKpYw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1TjF_qO-g5ovA6Qe0erHpfQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1YzbY-UcR0J5kxgDttoepvw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1AuM6h_Sy0PuZR68SdB8Vog',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/108W8l6CAQOOe7Jc4v8E5Gg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 29,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1YnOOE3ZE_ROTUB4ikSfI6Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 30,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/10YY6Z0Kx8-dBZZ0oCBACCw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 31,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[30].verificationCode,
        videolink: 'https://1024terabox.com/s/1x_sGXXXb50ulcsGXnkM3lg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 32,
        title: 'A Love So Romantic',
        imageUrl: ALoveSoRomantic,
        verificationCode: verificationCode[50].episodes[31].verificationCode,
        videolink: 'https://1024terabox.com/s/1BeMU1xinRirpTgDp9NCg7Q',
        youtubeLink: '',
        uploaded: true,
    },
]