import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyGirlFriendIsAnAlienS2 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1mEYBz8pPhpDXdu33JkoC9g',
        youtubeLink: 'https://youtu.be/JwrnjxkolcA?si=_R5j87Vd1h03V5Xr',
        uploaded: true,
    },
    {
        id: 2,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1eNvzG00SEKm1AigN4HBKCQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1fR66vLx_YHDly4daB7Nwsw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1klGvKIYDemSBJBAG3i8ucg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1_Z0kCjGo1KTgVkeI8Fk-bw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1_z-jjZ3tFZEOQ6PLaE7OzA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1QjEnXPFpG8VG5J_B8-idhA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/19pFfdVoLhdVFwK98xXwLVg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1f9dyOekK3P-FANQ2zREqEw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1WrGYwj9euYP9D8niSqK10Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1oj6ufzdsYC4Gns2WWV06cw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1nZ177LbXAMXxg-yBfFv4WQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1YRnVQXWT7BH5n7O5gIseWw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1bzd199K_1UXyGrcFlmw_zQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1NDnA0LLQCz45jv3RkH50GQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 29,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 30,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[2].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: true,
    },
]