import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyGirlFriendIsAnAlienS2 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1HiIVnV-5nOG3XciGkQFpHw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1CT_rtbmjkQN5QUe-DlDXvA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1yiqVMF6vEb1zrXahyJxeoA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1gxXyKC_UUVq2ZdZaouRh8Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1QUzEK3wAJBe6W4DbTDwpHQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1HA6HIXG8RQ_1hqzw26zWXQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1e6H8ONqXqeao4s-5lm0Giw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZHB5NnN_1Cvd7K8Nuu5sxg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1uK_azyC1Vhausdzf64aRFw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1t3CAbNfkoComsQGSf09ArA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/118t7HtXZ8VpovjZQi5Y_6Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1XtjWXOFdbg2cRXMRrYx_yw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1nS57V6Ny-ouJ6vRue8TtZQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1BeTS8Z9TVboo_OIRRAN4WA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1vCfG8BCOdxBeOfXhmQlvdA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1t8YhuRZG90Sp-bwN25-nxQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1cCxwtS7K_Q-HHcptne05QQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1ebC9Q2cTYLuZBNX12NB_Vw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1iPZ8iZuq9Wm0GdluseADzw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1BrLY0z1qIEA8N3aImVfcBg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1XEeVS9Mn0QjSFMJru7N04g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/14aJL__aaei8lk01Pudjx6A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1lJHxYJBpknv8s-NwleGwIA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1zC4EvVpQiA8qIcg6gUR-iA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/11c1tEn0b8ijd1pjZTKJ-xw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1NRbLDQ_jLYlvEbEFABldxw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1rmyKQWDfF71gKMjaCA-0mw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1O32HCqKsddaJAJ8ATt5FIA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1mzUA3u40bDo6DQ9ki2xe3A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'My Girl Friend Is An Alien Season 2',
        imageUrl: MyGirlFriendIsAnAlienS2,
        verificationCode: verificationCode[49].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1NsepdBCfHvIYI5Z-dv8GIg',
        youtubeLink: '',
        uploaded: false,
    },
]