import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { KingTheLand } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1SXz1Ldw8E5dHDsqfTTWpRw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1RxZJ4LN8Fk81PqxXvN9c6Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1S1KZQjVvjC1tOiSmujnwbQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1NNB1d1VXiyXeWZHVzh2j5w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1v9_q-UqwlSGffxsU48wqtQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/16BTczJZAGWbqhW0GJts18Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1WCTe-X80v5NX36bbUgWHHA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1HvcynxBgoLvY60kYGwkTLw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1ENrsuhJP6XqpWTF5uWxW-w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZGAvRwecWS3xY2bbzQHgZw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/10bXtgpEuxJVXK0HsCqsmlg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1xG4lCxnRpclBxokutVikfw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/14NiIKxYzYiUg4t9pgIJctQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1sFBAK1fihrgw1kcW8MOvMw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1d3443bS5nNrvGCEDsWcVow',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'King The Land',
        imageUrl: KingTheLand,
        verificationCode: verificationCode[8].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1fsnELiR7pTtooDtuDKbrbg',
        youtubeLink: '',
        uploaded: true,
    },
]