import { WTwoWorldApart } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '12345Love',
        videolink: 'https://1024terabox.com/s/1mEYBz8pPhpDXdu33JkoC9g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1eNvzG00SEKm1AigN4HBKCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1fR66vLx_YHDly4daB7Nwsw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1klGvKIYDemSBJBAG3i8ucg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1_Z0kCjGo1KTgVkeI8Fk-bw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1_z-jjZ3tFZEOQ6PLaE7OzA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1QjEnXPFpG8VG5J_B8-idhA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/19pFfdVoLhdVFwK98xXwLVg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1f9dyOekK3P-FANQ2zREqEw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1WrGYwj9euYP9D8niSqK10Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1oj6ufzdsYC4Gns2WWV06cw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1nZ177LbXAMXxg-yBfFv4WQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1YRnVQXWT7BH5n7O5gIseWw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1bzd199K_1UXyGrcFlmw_zQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1NDnA0LLQCz45jv3RkH50GQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'W Two Worlds Apart',
        imageUrl: WTwoWorldApart,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1MfC7SJ7DT35FNebnV6Y08A',
        youtubeLink: '',
        uploaded: false,
    },
]