import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MeetingYou2020 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1a9-AZ9oRyLRMkbB-us8vsg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1_0bGqwcwu6wdeZU4Ks1gvw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1QPjRA5RMv80zgiltDM69Jw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1bLRn_H7JsFxTPWlfXsZJZQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1TqJPXNfV81QYyG9zYJQUkg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/14z7A_IBH9_RrBwq-ZIDmZQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1f056IwhRVxcsKQUtKKefhQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ry2jrxsfaBtjt4vkYUlYTQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1m62snE4ESIMFqu8L_YB9qQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/17JLm8hjaWoF9C92--OcshQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1oLjbmwiN3cZiUxeZpUFh6g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/10Kcc_QV5COu5el1FbcqxYA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1kXoNW8DHNmyRAYtQLCLuaw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1fTucGuGPx6VFLC52ctjP8Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1tYwOPl58W_5-O4YDKtMWoQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ri8SPdKN8WdObsgPi7Qxmg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1YqIka-aL1ONzQz6BtH8m8Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1L_Z_TJj-BJydckRdZf05Pw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1tnHSD6hyvlLKO1E1WjhC3A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1mMphDntdqOKnbqJn-tho2Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1DVUkBcB1PBjrjE-RSMxL-Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1WeeGBHQMCgb0hU4mCkr2gA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1QIQcOjT1ojfdL7eGVJdvkA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1ByFaGJH-u3_3LoQC5kR5Pw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1cBSes2M5FXyEg87cvHbZjA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1RpXiVTfD4W7ebtbdB3LzVA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1CbqVc2dV2r-wQM2tsnU9Fw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'Meeting You 2020',
        imageUrl: MeetingYou2020,
        verificationCode: verificationCode[36].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1NmEXj9MElK9cLev03Ulv7g',
        youtubeLink: '',
        uploaded: true,
    },
]