import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { WeightLiftingKim } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Weight Lifting Kim',
        imageUrl: WeightLiftingKim,
        verificationCode: verificationCode[85].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    }
]