import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { BusinessProposal } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1IK6uC0g_GNNIHHkNrUCQqQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1_ErHjUbTCZ8PEqCwBbSGrA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1wP8nYbg-KLWQFb2LqUdJXQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1NOIVwIQfJ3Bn3zmX00xmOQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1QWFNgRiHG3QbpvenjZtJ6Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/15TLXeYtwwwS1CEVUhRYTZg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1IKGtDBFaSghspDDC-JvHaA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/17lwDxZu-5iZ-pZyVeXfX4A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1ucx5FcAUQrAPQyqnyAvc4g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1n0EjxMnv3oTHFhS2iWqfzg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1Dodd1I7GLsHZyvZosHVUxg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: verificationCode[5].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1newngfvKR0MvspFZsDVbBQ',
        youtubeLink: '',
        uploaded: false,
    },
]