import { BusinessProposal } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/1mEYBz8pPhpDXdu33JkoC9g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1eNvzG00SEKm1AigN4HBKCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1fR66vLx_YHDly4daB7Nwsw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1klGvKIYDemSBJBAG3i8ucg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1_Z0kCjGo1KTgVkeI8Fk-bw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1_z-jjZ3tFZEOQ6PLaE7OzA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1QjEnXPFpG8VG5J_B8-idhA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/19pFfdVoLhdVFwK98xXwLVg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1f9dyOekK3P-FANQ2zREqEw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1WrGYwj9euYP9D8niSqK10Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1oj6ufzdsYC4Gns2WWV06cw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1nZ177LbXAMXxg-yBfFv4WQ',
        youtubeLink: '',
        uploaded: false,
    },
]