import { BusinessProposal } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: 'Love12345',
        videolink: 'https://1024terabox.com/s/1CYgWdUdb8nKe7WjGOsgE1Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: 'https://1024terabox.com/s/1opkqO7JNwONylgOusRXtrA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Business Proposal',
        imageUrl: BusinessProposal,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]