import { ItsOkayToNotToBeOkay } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]