import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { ItsOkayToNotToBeOkay } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1JHuCI0cYrCTTFNpVxbhy-Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1R_zRFShr10ckWtXyG9VTTDw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1H6oxl9-c09oYYT_imM9nNw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1eZXGjSh10CCkSQ9RsJY3y7A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/16pjwrxYdderlLpy_01NNKQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/11DWT6L_l6ycyK4CiPCzT5A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1Q10EYwYXIwg942vsRanOjDg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1nAY_JgnZriJWO10IfdV9GQw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1d5eMMVvzDp7r16y9RAzlaQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1XXZty0tUm7sV3SSmkev6KQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1Fqnd05CS-pDz1HSY5VQA6Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1fa1zYc7uAommAglsW9WzuA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/10tAnJyrtp2bXu7tUGsBIhw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1MnRGzRjM_ViX6-rUJJ710pQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1G9Z9I_i10o-ve-phUYbsKEg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Its Okay To Not To Be Okay',
        imageUrl: ItsOkayToNotToBeOkay,
        verificationCode: verificationCode[10].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1CWKrwnalAu0hQUawqq1074A',
        youtubeLink: '',
        uploaded: true,
    },
]