import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { TimeToFallInLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZssUWYmSorq-cN0m-WpqgA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1suAQUjzFBpdFM0a8_8_YhA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1PJKhX3zR_RwyFfBVlI118w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1tf52bTnosG0S7Sx7R2qSFg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1_fPsIx3cx8uu9u3aRST4QQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1D_swA0UIYwThEpq-D5cYQg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1tHQ_26Trf5Aet6Qi1uvOyw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1j72EIAlw6f_83oqIeQnTWA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1LQXiPZAootAHOZswAPujxQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1pc5okeoyKWXGGDm7OBWIvg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1Pwbw_gjKFfuEsF9N1DoY3g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1lRFSulP92iH4GSfK5CaLZA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/13YlblSGiH88Rbpxs_vm20g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/12e8N0o9lKrBSIomE8QS6gQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/194HEnVtcyhYAG0l1HqUyqg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1n7Z-CjlwxHDenISQSFO-LA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1-7xc4luXVknACsHFl25nWw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1KwJGbbtYzGBQkN3GeAO0dQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1-e6gQmhCJHsLYMz06ypdVQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1vtUo1jTCa9HNNPyetffJuA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1J9Xq8TiJOkjAXW95qOxovA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1nv6VxE5Hnav3ngW4fZAOnQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1x2BTYnQQO3MA_MlUcszZ2w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: verificationCode[25].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1ADL0PtttavwA7jeKaB09-w',
        youtubeLink: '',
        uploaded: true,
    },
]