import { TimeToFallInLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Time To Fall In Love',
        imageUrl: TimeToFallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]