import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { IMayLoveYou } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1d6Wc10aL8hL4fb_jf9h9lg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1-lW9T36Y9E7um439y6NdjA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1tivkFVTKAbxoo_X1-B0Vgg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1tDaqefA3E28KfGS8fYSxpg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1F2xjqga-xalwFRvEDIYnJA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1vmdMVeESz3zRPnB_nNaZdQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1D4VMPcqgXOhmoyjK7hKxxQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1_kfQuVj2Y6KMEeRUAIYxMA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/11xxeRGuYLRXT-G0nKIvzTQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1LEYRKeq-YZjip_3ro3Ss4A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1pmBZCNz45I27zsd_B0g--w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1-hRBOg5F2N3H8bUYsuwEVA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1lM-N4mKxSG3P17kxTmok7A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1Jd0kRCztCCJnkv7KkxTOUA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1LMjW1MxDaC3xvyN6qsH9_w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1RdBYKLr5yS1myeWGEVDCog',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/19EoXXOaIsh0hBGiNew4Rww',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1sze7msrt0BrJ09M-E4rb1Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1antkeQ_d6bf73iY8Y4wo5A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1zHFnjB5cbRHERiYgy75yog',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1HJMKfuX1AmEbAFXuwpOn-Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1qoYAxUBtE3qthF5TS7Ppmg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1LqF5O76OixAWr3e32C09iA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'I May Love You',
        imageUrl: IMayLoveYou,
        verificationCode: verificationCode[61].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1IB8jP0hP93Av-_-G-b6LEg',
        youtubeLink: '',
        uploaded: false,
    },
]