import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { IAmNotARobot } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[24].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[25].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[26].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[27].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]