import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { IAmNotARobot } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1UJS7c8FY5nnGvTcrA5DUPg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1LVICcZNJ9OWzzqVLtEjgKg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1Rwp8CnxqvZJrFO_l2M79vw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1UgueFYzTlP-iHrpwRyZTQw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1D55pulW9xMA7dj0-8iRDqQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1fwD1n1nrX7WqQjrgvGJsoQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1CF_Xr6F8xoSBzfJrTOhEIA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1aT_67WxjLds-cT4fYVSZGw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/196Ko2jo_iO7bOiEDkprpkw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1QaM0I3wO2MaBFPaWNbRxPA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1EHdk5MktiCPqls2skP9kzA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1NdzEzyQWXdfCfj18NN9sAQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1OJ0kW43JIY-QsmdtIFpHeg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1gX9t2vw21xJg1iQr3nBWKw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZffyuPFqtWy7XqZ6mrGEeQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1kkzPa4oH8-QDahPw5BN-6w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1aKpkAN1O5oFfp5ax9L5L8g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/12IQV5USdpO3URqUdRaUosw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/18T1io4Li1uGIX3vlDa2dxQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/13zIh6AqwN6QNsb-he-A6aA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1D0WrtQGmsqJCVXviSGM7Sw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/180hfabSySduGFJdyn18sBA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/15Dry_UC5IsZ_JBQH2LP5jQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1ToAUOHWNplTOyUqS0NpnXg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1chygvRP__T7TKgkTQf9uqA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1E9Jm_Zl90wJz6dca5_zVkg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1Cn1xJigQMmiMynmxekDxQg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'I Am Not A Robot',
        imageUrl: IAmNotARobot,
        verificationCode: verificationCode[33].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1IuiHbGHhEw_EQNli5CFENA',
        youtubeLink: '',
        uploaded: true,
    },
]