import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { Heirs } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1C4BVTt3tS25X92zU-mmSrw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZxNWqHkoMfVyTIxZy8P9xQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1-lixvTIfYr-k5Px-XjydBg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1IBhTLGRNex5I1r_9pFqL_Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1SKPnUTNZLQPes4J9hMpalQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/12IACrlYtT-ySP1LG3bUeVw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/16qc-2Iuptqm2jCAKOjvRQg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1qaHjlAQqxSkyONOMqgnnRg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1Cfax9Cg8aDNTYAfjr9K0rg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZCdl0ehnqEcYlhEnD13OEQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1QCRnalhCjST_XF8xeL63iw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1-VSpXAq4tcBjzK3xDQTLOw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/10Ohh6jWxh5GEKZo3KetyWw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1NYOVeforq-S-sO4zQh9NaQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1t1fySD83mmTv0V_RH8FH1Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1N3pwTxTG_mraSabAXSyDHw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Heirs',
        imageUrl: Heirs,
        verificationCode: verificationCode[59].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1mHV7eAAs46oJLxShZ_EbHA',
        youtubeLink: '',
        uploaded: false,
    },
]