import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { YouAreMyDestiny } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1Zpu7MmoETKsKWkN15a3Snw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/18a7783VAT_6us8u6HxZVxQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/15a3TOagIce43NAjrFKOiJA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1FhLlaADajAaHGmkURZW9mg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1B3AaW06rOIU9LLDZ0mK64w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1IEVgFagKv0oFdyAmxIkz1Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1PTyXCON3ptAJ4d8QsAHsPQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1FCatsoH-rnBdSFDea3T-kA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ec_scisph5ggHHoyqQI5_Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1F-6wT3IXzCWIt8uVUBB9OA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1-Veeeb_g1OKw8e8oWXXujQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1gIH_IYpcPYlTq5d6gV9TaQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/10cI4RJ3bGbT2sma2Gwsolg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1ftyuYFLSm8P7VifWHRCi4Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1nLtLdw5k93mUeYZk_nzYqA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/115vvCyAV-miIGBMRs2xuGA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1OA09i7V42kyRCMoHOJ7A3g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ise0OYUKbmrRDAvNh7ZqRQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1HiVjUC482Im94aTrV39SPw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1P5hTiQjD5xUkyJscqoH0kw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1dIfnTL9OWp872ewFLmFbRQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1MYr4EpazMLAQbr9fxadcYw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1UIYbLqxlsCSeTBsxD1nMnA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/14U6ivg0oaUU5z3sufTOk_Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1v_41lpskzOvVXzF0SqNFpA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1Z37MTsZywTa9FVbSx8WVbQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1tr6LIJkQ-MK78yzIM6TUvg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1EHA90Ja_L7qim8EcoGWyeg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1WnAMx9DQR2jf7ADpy8XjSw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1d5psADpj76Xk_vBO7b-6yw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[30].verificationCode,
        videolink: 'https://1024terabox.com/s/1JAlGRhBicWEHb-Omx3I-OQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[31].verificationCode,
        videolink: 'https://1024terabox.com/s/1IXoO_FXzhnXO9MLRCnPHZw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 33,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[32].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZT8YHttq1PQ33G1Gd2GO8Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 34,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[33].verificationCode,
        videolink: 'https://1024terabox.com/s/1bJRIGsx4R4Vo_BCr3yOOAg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 35,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[34].verificationCode,
        videolink: 'https://1024terabox.com/s/1exl4qav17qO9esNS-BA6ZA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 36,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[35].verificationCode,
        videolink: 'https://1024terabox.com/s/1WkFhjslo1OL3RE3wB65bpA',
        youtubeLink: '',
        uploaded: false,
    },
]