import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { YouAreMyDestiny } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[26].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[24].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[25].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[26].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[27].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[28].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[29].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[30].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[31].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 33,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[32].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 34,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[33].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 35,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[34].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 36,
        title: 'You Are My Destiny',
        imageUrl: YouAreMyDestiny,
        verificationCode: verificationCode[47].episodes[35].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]