import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyDeskmate } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1OlSHlmbv8S0vMEIYEYEfAg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1g3MlrQ0tKm0Ayc8Ka-lEWA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1dI0h877kLLCZTMGZC1FUVQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1SkLPnVcaDz5SsVD8v0O-JA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/18VhwsmB44I8A_fSurxd0YA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1gIIM1JYEepDmWcU7wp2jaA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1J5SGT1R1XXU_c6ntCVtvgw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/194TzewUUv_BCGhyAXT4skA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1FTGwhvUSQQwag3KC1xsIyA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/13uiXnA3m9SeIVjzldIpCsw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1l57K3e76MSgR1UkCazUeuA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1mUEroUaEpvGufXy36Dx2xA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1Kbz5IJe-4_m-sUmVPAsANw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1EDOPwl2T5R26AtX611NiMg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1oS3r9pqpYcyGDY0Oj6D7cg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1drR2YGNm7jBB2CjzIwuMGA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1bjEK9jbo6m8uq8VoL9UxEQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1hcK9c5zgk9XQ_eVCkkGsXQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1iPQJKEWCR63RSUiKPdXjIg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1xKchK9V9OIcQmx9cmF4V4g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1BEuL-ICQHNxRygissRgo5A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1NtbpVzswbad_UAjkHvE2_w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1HGj2dHwfo6RscNBZF-XMQg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1jpjfKh8GC5X7K9gvZLeVRw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/128i1k1_s_IJjDaKCFBZ1fw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1JXhnLiiockSyI_XUbjbgrQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1RC4ZIVr9whrCo9gObQYaHw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1c-chJkGdGGlJyfNTfwI3Fw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1llRuzyqFepmgJ4JOvibZJw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'My Deskmate',
        imageUrl: MyDeskmate,
        verificationCode: verificationCode[68].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/12qhfByAD1e9caYsKW-JP6w',
        youtubeLink: '',
        uploaded: false,
    },
]