import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { OurSecret } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/12x3CkZnmqzTxTdlOf5CZ_w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/14bzEwljWCGEGbURD1vNY8w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1F__XSmonTSubkfVt0QAWuw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/13RAuY54Rqx3r4lP4DBr9Fg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1JMe1BIUSWY0j3Cr5K5N4ow',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1TfZhJZocaOotqU8bDDA0fA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/173UH-bVG2sSLMiwx-BPYTw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1CX86_39JEpchZ8Hoi6PoYg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/18JShs9hIGH3cN3XMp8xcuQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1wWPmwt1FIOrJB27tcFyUHA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1a8IzV8GKSa7yab-mLj3xZQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1Nkqj15xFjQnrAzyB_2bI4Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1dZA_HzVifQRWNc-eZJCQ4w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1_E55uIe3zQRRF68V896ukA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1Bis5TzfSPR2tYXM4Ldnklw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1B1Heeayy6rtTgTRDb4eR6A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1vapntibkQDIJIv6JQyS2vw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/17_8Lmnrg-aIw0BOeCcv2Ag',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1PUxyVGGGqu_k56rzQ5YGPQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1FFQjlWL8stXuEMX4DYM0sw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1oCbXIwsv-s6rPCNmmj-QUA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1SPQPl9-x2G0NIFhFMoFo3A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1oSi-q6BzHbLErz6cd_WFww',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Our Secret',
        imageUrl: OurSecret,
        verificationCode: verificationCode[18].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1DNE8Ku_2kgonhRWe8d1PUw',
        youtubeLink: '',
        uploaded: true,
    },
]