import { DotOfSun } from "../../../../assets"
export const Episodes = [
    {
        id: 1,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '123456',
        videolink: 'https://1024terabox.com/s/1XtU1tTFSN7q5z8-SSrnSOw',
        youtubeLink: 'https://youtu.be/ppgFkzQ10ow?si=Jofn2FQiGjkCtjbd',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1O4WfJqi84e9saH_cKt8Daw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1wt5pY2bM86638x8kPAvs5w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1khbwPRLYrgVPW_7UUtJPCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/16G2_eONjXWRhBih-utDUfQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1EqetdXvYfvfIdbARwHW1RQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1nLyAeXDDJBE5-AP8Fs9azw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1U6gvOuno3xutLnjWuFlu4Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/17eE2UsAo-RqO4e9l-638IQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1mJp55JxZbyP_HPv8Nab2eA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1bRvpqM9QgCxOsHkXg-YTCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1Sux0v2agUtQ2frLAsVFxSw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/10nKMkBzzK4KzLqp_-G05_A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1Oqb4E9O9gCikUYQ2QjGM7w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1WWSbwuOSxzFToNJkLUMuSw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Descendants of the sun',
        imageUrl: DotOfSun,
        verificationCode: '654321',
        videolink: 'https://1024terabox.com/s/1S35BiTiNGjwayiFp9Q3SuA',
        youtubeLink: '',
        uploaded: false,
    },
]
