import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { DineWithLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1vmO2If8W3zOr6xE_q8Gmrg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1rCzsAr0PCNxeVbSuPcNpkw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1eU--9civILGrviFOmxBRvw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1SiOhRchn0Hgzb7issPUlBw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1lueS2Hqx7d4SqibUKsjiYg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1CQblSlA-DavV_T-WCyQVWQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/14eJcAp37T-WXTbprqvR_sg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1sLymTbL3YxFTeuNk6Q8loA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1zluVbl9-0Bv5LUdazlyNTw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/15Nm7EukGdc0_lGxGAEzXcg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1bNUEbVSX-pBfz3Q4Y3_Dlg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1O39bRfZHDSaBOwk_MFh9kQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1iqrtHaNceF6_mws82Fh34w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1T4d1mU91gcCW3AnW8lsh6w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ln_rh-5eTRnkmw_Yh9szNA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: verificationCode[3].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1_T5g9binUOgCcIDG2JibiA',
        youtubeLink: '',
        uploaded: true,
    },
]