import { DineWithLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: 'Love12345',
        videolink: 'https://1024terabox.com/s/1_DH8ddgvNVpC3-kQY2kMRg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Dine With Love',
        imageUrl: DineWithLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]