import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { TheWheelOfTimeS2 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[45].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1uCToWnm2mionKdnfpJOGOA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[45].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1y1QOiLtuCYSIJcy5x3oHeA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[45].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1UhlmHntQVHaWn161Wo75Lw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[45].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1kYBOFdOT2TO90PgPcWMd7w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[45].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1po48IUdjOa2JSZ6jofYqCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[45].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1kmaBHXF0iBDSny0Qs-Vt5Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[45].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1TpRg2PW92RqF6Xs2uMai8g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[45].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1OelnuH0QMeHz5-UWA3VWGw',
        youtubeLink: '',
        uploaded: false,
    },
]