import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { TheWheelOfTimeS2 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[2].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1mEYBz8pPhpDXdu33JkoC9g',
        youtubeLink: 'https://youtu.be/JwrnjxkolcA?si=_R5j87Vd1h03V5Xr',
        uploaded: true,
    },
    {
        id: 2,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[2].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1eNvzG00SEKm1AigN4HBKCQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[2].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1fR66vLx_YHDly4daB7Nwsw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[2].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1klGvKIYDemSBJBAG3i8ucg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[2].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1_Z0kCjGo1KTgVkeI8Fk-bw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[2].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1_z-jjZ3tFZEOQ6PLaE7OzA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[2].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1QjEnXPFpG8VG5J_B8-idhA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'The Wheel Of Time Season 2',
        imageUrl: TheWheelOfTimeS2,
        verificationCode: verificationCode[2].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/19pFfdVoLhdVFwK98xXwLVg',
        youtubeLink: '',
        uploaded: true,
    },
]