import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyIdIsGanganamBeauty } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1wpTX9h9ovqSwVG0eaKx6lg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1UmShiZjPZO6X2I3aRK8aKg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/11_aDxp-mTL9YdGhyG9BOPw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1joTgDuhjZXufd3dXwn5m4w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ce4LWQ_1ooSI8OoFouU_wA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/15t1NXL3NDotNr3sLvKeDxg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1VUvJpsM1oEZ8uE6Hr6mDhg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1TQ11mDPQfg46V3UrIl7_3A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/17AKzV9bam-YsBpWuqRBukw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1Sn27OflhDQCrqtVImDSzwA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1YJV0XDu7tfayZyPqYyuKKQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/19MpzKQGLe2pRng-4k6rbvw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1rEuWd73BImmDy-lOITpOZw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1uKTVhzXjilJzVicmcyanHw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1nKOz3Qng9RBrXfzXcZaZ5w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'My Id Is Ganganam Beauty',
        imageUrl: MyIdIsGanganamBeauty,
        verificationCode: verificationCode[70].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ahe4oL8fw0zg0xXcTtvpcw',
        youtubeLink: '',
        uploaded: false,
    },
]