import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { GirlFriend } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1M3x1xZaRTkFlylbD3_o7Sg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1EzvCIaqugk-HShUkhvdvVw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/122a-Bk1CJmhMAWsGoJHHIQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1fst8DD5-wTbwUgOUGma4YQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1LqnhRxROOcXUTPFbCfCsIQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1-Sp1zSo2Jv6ZdBKDGohjxg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1LQos7eVlR1Totzd_gUV2gA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1Z-eVjFnKeg9THGCa4gbyOw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/12eqBpQhsn4BD3dxvjL4bNg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1KOnR1lHhM-n-dx5HMpYRlA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1NAAnUwsyTPrWXKSNutYy0w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/19LX_7CcipzP4LsT9mgNzeQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1IEahvVZ4h_TGTEHYMdgYbA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1m7FIVMKNDGBydoG3VbqB4A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1O7wXPZCp-bI5vM9PgSXK5Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1C1G8dMwxtG1kdrmfMMzz3g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1IyfdoZnzKv10U1D74bS5og',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1nZQNYMVK5xXFZMPO-KA5bg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1WZzGDZ9cBafvzcODI5gmDA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1hkTBcXhaSgQ-veX_1CEj-A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1wsKofRFr16B1PNl9yLqc3A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1pEhmSZaotu6Z_nPOku0-nQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1H1Eqzdh0hlBE-wekWDDraw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1nsltirv7S0wmJMUtgYPKKg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1XexTJtJ4SnFVpRrlOqPYyw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1wSxtG-SFly8M630okNexxA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1n3N2Adn7fbf5cl-kmp8T_Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1oEVnPsCx0cYS-ILXeRWjIA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 29,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[28].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[29].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[30].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[31].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 33,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[32].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 34,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[33].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 35,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[34].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 36,
        title: 'Girl Friend',
        imageUrl: GirlFriend,
        verificationCode: verificationCode[31].episodes[35].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]