import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { LoveMeLikeIDo } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1EgdnNlU-vJcwBLLLyROOZg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1gnuOohLCe1drrqbqbuezxQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/152KkI5rV0we5onTldh0EgQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1G9nmGF3njqQidt7B_PoFLA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1CTzxpsY6hfYjmCubd9FW0A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/10NS0X75EQTZ1VPJitwfFAQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1QEMau0SlFOgPgmVQiSwqAg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1mEWg4Vw-GQ_uvLIquWnQ9A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1ir9reZ5_P2WMFO-T1YWGqw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1w4H5xml1iWlasU-tYOpEcw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1RDoruCnrQNcma5z7rfKOsQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1jtGkFEM-wuomr4EM51Wkfg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1e5xWAHdcxz1TonGGIQkBxQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1WGNJY6_Wx5e36z9kQ_wzfw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1IpL11fqyAQvV11O3QIsm_kGA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1-JM3ArYMZFLE9Cx3LrURRg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1SzhuXBpMjGKD_EK9rtVEvA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Love Me Like I Do',
        imageUrl: LoveMeLikeIDo,
        verificationCode: verificationCode[11].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1AJ2PkIbAnVIQPDOdulBKfQ',
        youtubeLink: '',
        uploaded: true,
    },
]