import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyGirlFriendIsAGumiho } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1zT9Bzdm2WZOK9yOxU4tVNg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1LYsuD_tXsbH8IC54_UmOoQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1tFAeNXTUQAyj6_mNLiCxQw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1C1YY7rKXWZ6wuUxjFdU9Gg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1RGVTE-39iOl4a6uwWtMPoQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1W-P6vNPGNqQ75HBpeo-phg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1hSjrIuOWRIwe7RCb0IbZ2w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1D7PI0cRwyUSzE4ig3AWepw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1TufonZznsuhvOcbiyhZauw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1Qhygrej-7qOWHvLY_viM4g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1Uhvr3gfpg8cD1GGaVM01dw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1XrQTP6TZB07DMmF7W4Ra7Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/132qhTmJdv89m3oQM8e_KAA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1QmqDYpE0xh2g6dzg5RIwpw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1EUlAU6wSq7sRgaegv0b9Jw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'My Girl Friend Is Gumiho',
        imageUrl: MyGirlFriendIsAGumiho,
        verificationCode: verificationCode[69].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1p3zTwfgZymyBkixHbQTBoQ',
        youtubeLink: '',
        uploaded: false,
    },
]