export { default as Logo } from "./logo.png"
export { default as DotOfSun } from "./DotOfSun.jpeg"
export { default as LoveIsSweet } from "./LoveIsSweet.jpg" 
export { default as WTwoWorld } from "./wTwoWorld.jpg" 
export { default as MyGirlFriendIsAnAlien } from "./MyGirlFriendIsAnAlien.jpg" 
export { default as LoveScenery } from "./LoveScenery.jpg" 
export { default as ItsOkayToNotToBeOkay } from "./ItsOkayToNotToBeOkay.jpg" 