import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { ChasingBall } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1x67kOOOfbpqMOuiCPZfiaA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/11r4l_8mkY8P4bersMxAMZg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1f-BEXVdjQcYwaX4VkQfwtA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1icMqyeSGOsHiPHTwROmmFQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1762jw6wIzJ-LuuueamqfBw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/13TTLXo1pk7fjucEHdoWAEg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1XpGIS-DEX7lU3i7J_sB32Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1IlvgPRULUNfwhZai7I33KA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1q5ccN5KG8f8CNvBbjkZj8Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1Y9JS5L5NxnNpTw_QaNL4eQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1AFE6P9uXdCJxFRZk3rlT_Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1FyNYhjvOJYIt0cafgp_n4Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1uOjVj5N3oJpJDV7_8AhKKA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1JmL7fC7bL1Wkst8uS1vUWA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/12KJhzwHulAK3KCnnoiPFUw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1Bn-CfX4i7MGYHL_yGvEkkg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1Nt7Qk9irWt2SQ0TR-8NVDQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1gNge1Tjs1FZp2MrFsy6SuQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1puiDwwOQQ8SgEg4EHHP22w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1pi81qUr7p4AQF0RM1qVApw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1JX2R8kU6qBeJXhf6OoQ12Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1YuPxYCBlsprfTVBlgzCI6w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1PtilPSiuirKeIpLXQqkitQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/10RawojKyT8LB8c35TzkA3w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ixk_Jg1SrvXBuo0sbTnefA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1g6ch-TgKsydfmSYWq6rPmg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1vknYqTlCH9WtYL_KyFnB7A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1tXm-5adHB0OEl8Q4ekwebg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1pLLn-6OQz1WT970wvbCV2g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1KRYEEDi2YdWi8GK7INlVtg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[30].verificationCode,
        videolink: 'https://1024terabox.com/s/1KOm6tHaVwazsEx6CfL114Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[31].verificationCode,
        videolink: 'https://1024terabox.com/s/1zFiJBceJBvZ4chpudiUQAw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 33,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[32].verificationCode,
        videolink: 'https://1024terabox.com/s/1AOIEzFrzs1a2JU-8MqEuhg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 34,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[33].verificationCode,
        videolink: 'https://1024terabox.com/s/18FoYqdthKnMf_SLbFEl6EA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 35,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[34].verificationCode,
        videolink: 'https://1024terabox.com/s/1l7DDl_bn_8g3NzbfxHIS-A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 36,
        title: 'Chasing Ball',
        imageUrl: ChasingBall,
        verificationCode: verificationCode[53].episodes[35].verificationCode,
        videolink: 'https://1024terabox.com/s/19sEUbaOOdKiBDUFwu0Y90w',
        youtubeLink: '',
        uploaded: false,
    },
]