import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyDemon } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZeYPkYSYa95Gjo3-L3Gdvg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1SpW9shSpSaqEGbV_9sIjow',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/19__ERl7PmFjOIdfhhg62iw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1wZR8JYah7P3GTsjAo6bcgw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1-ACbDECoCujNZJSVIX9dUw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1kKPgaZ2XH2H3TPi2Qzfj7Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1iJJwWdBs6bijWUMEKUYPKA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1XucEPJVVXnwqV06jqJ3alQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1QR6KFQKMZHuYoOExsWq4og',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1XyZQN6yQfWR9Ggi99U2D8A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/10-H_UwbdFscs2VsHWN6F1g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1bMZ8xKSLoYZz4hEc6skHLg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1jWgBXQBu_YAwDZDlGuImew',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1G0Yh-7Qu0UOwmteOU1s54g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/13oxjOVXHGkl6YerWe5KRrg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'My Demon',
        imageUrl: MyDemon,
        verificationCode: verificationCode[16].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/12Ak6d4I_2pX0bkCBJ-RBEA',
        youtubeLink: '',
        uploaded: true,
    },
]