import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { StepByStepLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/15lnir7Y3w9mY8T8eywUXbA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1p816qZj5Zz8QJ_hsxgLY9g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1dGMmAXHbCxVrnCXBuGm34g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1OEZqUSb0hZ1awYD1zq_4mw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/18d88zRqxiajO4giVE8GIOg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1hEbon1kySpv47Yr2b_kzYg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1TL7M_z1X8tWAH03gGh5K6g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1xYgZcwux930TZ19oH24BjA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/15VumlQA9LslRxXbAwO-Z_A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1lugnnP4ujzH_pCQySe4k2A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/18_sh3BkqlZAvY62rUMbjtA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/18lU3RQEtq9d7bsV_gQLmGg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1cn7KpeBCnNUXzSBaDJXPig',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1SwRe_HsAGrYG4gLG3EcHKw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1mI9PlR2ylIbTIa37XHdS8w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1xID2vSqODgtQyEkcwk1q9w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1ejiZJo0CFPfnnrZkhjoivQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1Hh8HSCIAtL47zqTe-6IItg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1ALRe2zfft8d-5A2pBVlDlQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/180f6obGPQglGdwQ2g6XFfg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1M1UR2PG6POvysMWaJvV9Ug',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1lf3N12yzq3D2-4fmG3FSwA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1Kj3DgYINM_bae7w7tnv1WQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1C1jWgfbnyVFU0mZj8594XQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1_ZKLy3bS6j_B2SG215Pp1Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1pYfGMxMQyirLLqyTOS3yAA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1DaSBwTOSTaNiDO4FtWD3UA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Step By Step Love',
        imageUrl: StepByStepLove,
        verificationCode: verificationCode[41].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1U7nX8wN-p9PO_0FpBlHlrQ',
        youtubeLink: '',
        uploaded: false,
    },
]