import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { PutYourHeadOnMyShoulder } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1X7EPntS-VBNwq_eq3hQEvg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1LFx1JlEotDWrYUlLADyBwQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1NU8gw1AsaoOLl0M7f9LZyg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1M9N0KhsPjauoyT2mTyPSbA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1szDD5vlgyLFgs6ZKOfwP-w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1yde3FynZLsmnHqlMt8PArw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1iJSeL7Njdy1ZxrWlpxdliw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1uz_3m0HCMNDyzkLYSGwbFw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1IaiHa6DBjUUkyt6QALKWnw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1Vn0dhKmOz-SU1wg4l9f05A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/12EYQtnVauBheHFSZ9BKyHQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/19jACcqUDHMQM0BI9o18Y7g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1vGQlFxzE7NWVRnhCuyZ2wA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1jTUopq1gpS9Q7HkcBnLwEw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1LLXsVXXo760y5nDSYHOo3g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1RF65Xll0lm-G53XIyMFWWw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1sehyY7mq2oqTAVVhN2rjEA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/16yl0Wi5MeOSfGlxjKFufCw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1Zl4QA9mAlumRKkQlQIHvNQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1N1NXy0dKcEQs5GRdgyyVTw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1eqgh9JXfQN4fyyhu-kOmXw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/16TqYp0GuQOMK6jU__bNzCA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1ghkkahn7KgevxbjmGQrFJQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Put Your Head On My Shoulder',
        imageUrl: PutYourHeadOnMyShoulder,
        verificationCode: verificationCode[19].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1CjFH1Ce6OyqIw-hDWtbFgQ',
        youtubeLink: '',
        uploaded: true,
    },
]