import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { LieToLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/16Xmr1lLeLDtszFmkSdH9YA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1L4DTT4KBOkYICndSQmhWuA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1CE5JR9A1_vsqJG1VXdVGzw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1cwbtFBRjl67KyorHajJmHw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/13V1LjX9p7nYP_H3RhAqv7Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1MAtjov-bFukTLYkrwtzMWQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1FHIgrDLMBUcgQYZVdaFOjg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1AYuKRAYcKtvbZXcNHNQrJA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1V3t4_xbCZuumCafhC0mJyA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1I_ycyRmYt7PwCe3A21220wA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1PSw4oxQm17XB6szYwz0Xvg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/11lLxEjN4_36k6lBbRunJrw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1-DRavKd7r12sQMjaISeIEug',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1a3XeAQrnYoNa94dBrKsawA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1dyjiI7g127uP775Po__JlzA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1mABKZp110Bks1t127V4xYIw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1hoNm9uO1221jKHquNyeZ9Xg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 112,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1J5ZQOrJslnDW7ENp0l0kKg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1TLhAVtNQqDSbLr-kA-UAGg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1fjPso7SnmsKLoNhEbsXDLw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1sO2phMQzVYp0sAgStv_LUQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1UYAR-GtubILeXJdtQNXhQQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1VnmP6eahRS4RW7aP11212wXQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1TKXkYJsasP-NS9B6WTQzXw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1yG4TnvykpwT6GkLs-W-naQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1vWPiNQ2I7uyUTtkVtdSDvw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1jOg0-lV3fbZniK_dY1KAiA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 212,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1PeZP0vEfdmJChfVtwGQUlA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 29,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1zmVwPfn9TH_WY1c-cCgRxw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 30,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1jfSteQzJ-bunL09wTGMKcA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 31,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[30].verificationCode,
        videolink: 'https://1024terabox.com/s/156DgYQfxSB-SiXy1XKrzqA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 32,
        title: 'Lie To Love',
        imageUrl: LieToLove,
        verificationCode: verificationCode[12].episodes[31].verificationCode,
        videolink: 'https://1024terabox.com/s/1t5AkTD23lu_qnFWnZhIK9A',
        youtubeLink: '',
        uploaded: true,
    },
]