import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { DreamGarden } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1nmNOauw03LABi-EuGfXBFg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/14jZGgTuPCGsAMKnv12nneg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1svLJQqDJBImsNYfPIWJuzw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1k4T24YBQv8EAIUKWm4k3qw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1WXIynxhM_WiTOpdpzppu7Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1f3uf-34_kXNvt1276RBnTw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/151uPr5VQIPInxkZH-FjgYw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1gDIoex19MeAoMGCE9-2wDw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1FspoPFZlo1WhBJMwbV6Cwg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1mUnYEwIJR9T9oNN3OiYJJQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1iPRzclJwZSefuQp3WcOaEw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1reOmZeXDwbn-T29NsklWMQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1DJ93yGkAK_bqpsyNju4tBA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1GJkhgusQZp5BCXi0Buab4g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1ApOmqfIyTHg91xiqdDu-Rg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1ay83Tu1hVBQanl4FLDsLBg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1hd6iAmeI5L61IdPw90BqLQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZE2UFc_fN22Yk6ixSoOewg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/16iYNltLiig7AiIATrwebvw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/11oRKHYCcu-21PauG6P3MMw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1nW53KEA-Y4gkz3uKkYkksw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1iqYHv_lDqCzRqINQGQ0W0w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1HWqhf-mK2my_knQMT92Dpg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/12IoSSrlzM2TvGCQgKTWVog',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1f5lBi9Zu_AWmfKcF314Big',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1LAWnO_hYFQbRSoQhdhQiSQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1u3nPh8YmOMPxYcnP8BKl8g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1UAo9gO7zOJKE4WVS2E5Y1g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1B2lkP7vI1R-Y6r1DGuJY9Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1h6BI_TWZLZAfLmbIN5M1RA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[30].verificationCode,
        videolink: 'https://1024terabox.com/s/1nSuDJ0ovmgBRAV0QOU7tlg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'Dream Garden',
        imageUrl: DreamGarden,
        verificationCode: verificationCode[57].episodes[31].verificationCode,
        videolink: 'https://1024terabox.com/s/1blmq4j-UdzvYlillS5GQdQ',
        youtubeLink: '',
        uploaded: false,
    },
]