import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { BringItGhost } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1eXAE1rk4LAcE8MXKcWFB3w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1aT3_IYVw-jDgOgY3DATr1g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1eOpkcz2bf1B9OVwxbsijoA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1CsKVwYUVDa0hSd9O9xCz1Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1pboNt3VhjBiVktzOCoPJzg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1lS1H3hmnyePUkL1yUBKEhw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1F4lSIKXbj3K_S_5pELtrPw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1WUuXxZmaAH-s_khUsRPrUA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1vMgk9AFgKqoKf5XEwV6Ajg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1TGng9JvldqchpkP4h2tlCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1cTr5Gtnt4ykun6KQo7Qk_A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1Od0kUqtXO7EgL0RgIrdnxw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1hdO0qe-uWmeWaCfhP-GNTA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1v0uoAoNGTB4vdouCLVx46w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1xfq5H2K0k98B0L1t9uLJdg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Bring It Ghost',
        imageUrl: BringItGhost,
        verificationCode: verificationCode[52].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1fgqYp84INoP2UTaklhn36w',
        youtubeLink: '',
        uploaded: false,
    },
]