import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { LoveAtFirstBite } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/14blvLWeANJipAKF4lPyVBw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1gzsKPaxtSMC5eWuPrQ8GTw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1ljn91OngC92QM_cQjwc7rA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1ire0w7k0rT3sgSKTFib2Mw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1viXTgu79IV0OjhVuO9_1Cw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1NxxXqjAdoCxjJdidm3UTkA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1VH096ObFqiax4_R7gIQhYQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1NjMjUiJc3xEX1hcEkClVxQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1rw6-B0sbvXCodYUZCS62XQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1GhHbb5ojB6QY5gMlo2CWww',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1YjlSBGOHb2b6Lig2g59yzw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1TT2_jMbYrJ1qYCbrWsPP1A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/18ZTKDxExRmw0aQt5VY4Bxw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1UxJK0_Y3xJzXf5AB0QWGew',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1foIoCMXUkrIgq8MdYw7MPA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1TeSgRZ9YgP_tDR9BHsp_rw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1JzXyx0PH42FH05yFWI2pkQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/11f5Gw6AO295CP34DwUIIXw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1sqTQnW0o2LP8M3VxMxAT0g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Love At First Bite',
        imageUrl: LoveAtFirstBite,
        verificationCode: verificationCode[63].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1OKk3cl5k2rgCQ6DAqVIJnA',
        youtubeLink: '',
        uploaded: false,
    },
]