import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { EternalLoveRain } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1x4KPsnoWNjvAjcCqwfSiGA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1DLetIUj7C6TwIFe8u4X7Dg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1pNz6r3OpyOhwuHuBTB1jcQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1iPg2RzfsQClNC-hkzqej9Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1kyG70JtTIuRXFenWdPS03w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/19nxdhH6JspS8Ti0X5uzypw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1r-TIoOj9W7Fz91CRg381QA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/12aWMXKL-Gw_-Jg4A1t_aMQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1nYLsVHcurH3F4uxEz6bxAQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1gkKxZikAyBOgadNw6GL-rA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/19p0V6b9CHPU2Hqx_gdwqiA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1SzhvF3tL-sA1gmKnFy5vtQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1T7TIT07ZiRRv7y-OZ7uIbQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1jhnMe3LM5W8WPJG677bOfw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/18to29blm8HI9E_2NB5qBCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1jRaviiLyOXVVUsmpFxT-Zg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1sveM-gdLffvEk73LHAr7EQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1H6vUwafEBCOvsvwhcKfd8A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1NWlVuHonmNIb8vTc5XmL9A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/15f2eFfcaHODTn-UjnWszlg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1XdgOvh6VX96keEkIcCpE8A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1vXxL50k7YOydXQ1FjRiIFQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1mMDhR_yjaciU-rARySBCYQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Enternal Love Rain',
        imageUrl: EternalLoveRain,
        verificationCode: verificationCode[58].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1SmlM8_jtR2MicCWvjlk9Wg',
        youtubeLink: '',
        uploaded: false,
    },
]