import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { Love020 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1L9S8gqwnb150N2Zdb8WHFQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1GIC7sgD7zbGobU0tCc3ypw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1t9qxfQ672WXCESUfFwTefA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/11w-oHcbjUMrH0G9-x1QU7Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1mXKt6vOCf7qeYEQJZcA2ZQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/19Bu8Xnj1Ioe1u_frKYY8fQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/13fepKi3JBbnrq59OeAmZqQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1Sas9jO55vX5H8Yzene7tFA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1QqdvBZZiLHG5Qyl0hpDArw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1murynDTmCxz7eD7vWD2gcg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1I_GqkrHQX_onMrw3KSqTfg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1Flsz47CXGhg1C7OmXMfztA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/15YdDRQe2y7ujFyB60PT8VQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1GWqgP480aUJ1nVVzWGGwWA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1P3qwSWDtocZ_l03S_Lix5A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1kMM-nMaDm3p4OT-4F7nGzA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/17PPvbfbzQA75vbneFtGL-w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1riWtQ1s5dZBdbZyXAbH6Bg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/19mgJ8mWYMIX1xmhoq9dxtA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/17m81WleBj1P6-ii54_wiMA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1btusqbbq-atPBphvDuhGcg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/12CWF7FuvD7YXHixAPAUN-Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1N3uDZ3vwDPzTcMSxx95rHQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1HSoU4sh67ekOefAcsQkA4g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1j6TP4E13qUiWjtAj2a_lDw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1357dupZ5mUle6TZIqRO90g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1c8ezmUUxRv7V7Zf3WWPjPw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1v4viT6LJ1BeGcOuVCK5GkQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1L_8FWHLjEmrtGLJosQvqew',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'Love020',
        imageUrl: Love020,
        verificationCode: verificationCode[65].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1_Hi9fmI1ZF59x_wnfcxptg',
        youtubeLink: '',
        uploaded: false,
    },
]