import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { TheKingEternalMonarch } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1kIZdA-V_EgR8CNErT5wqJQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1R-vYcnnSa4du-CecScORTA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1nZAInZoJ52yh4mHEG_m_kw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1yv9Q_kXWJbWrliPkMxQbdA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1U_ejQztOqGyqfpooIVSQJw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1tlEeB8um6kn4pwXifhfRSQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1_pvtZmq3pf6q_w-U8_Km2Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1_Y6SRRda-Ow1Kxj9ZteYtA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1IDEzWYYyOY8DTCinFCQWeQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1YTw4-stRWupLZeBq8sLRow',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/15Xq07pIiHHBWAWKccwNf7w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1H1hyder5kLXjIqRuiO5dtg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1P2y9WGEo-a7uWT9h6EgAvQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1OduIbTEuOOx74mQ90-sY_w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1ya8Pg7tgikVJd9YTrnfYYg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'The King Eternal Monarch',
        imageUrl: TheKingEternalMonarch,
        verificationCode: verificationCode[43].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/19_BRphMcDhasQzvRvVV12Q',
        youtubeLink: '',
        uploaded: false,
    },
]