import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MeltingMeSoftly } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1GX3_JMDJYd8wvU6JZCas9Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1vqH6PHwk8KKGOjPg8f7UDw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1VfWzrutwEOcq0Vs03IZZ0w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1dI3YJJkvP-iw2ObR4reO9Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1dltDe1F3LuHnLUOvwUl7jg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1GuzdNxGBk-ds9Lav8euVIg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1q8zZRDMikt-UBMRjDEAcoA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1t4a8ldloFQ3PFywjUQs1tA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/15OW-1V5JMjcrnd05fAhAMQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/13pBlOC5sRACMiUQsP1CIhw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/18wmmASugXkeUMihEqU1B8g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1mF08XxOleJMJewR_JKtM-g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1WYjWKAf_rSUte26fhH6EuA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1c3T1Zo-6dLzCGMK1N4anEg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1jAtvgtZixD3iiPE66Z7hoQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Melting Me Softly',
        imageUrl: MeltingMeSoftly,
        verificationCode: verificationCode[15].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1n0kGGCZxQ19ZOEurz3--og',
        youtubeLink: '',
        uploaded: true,
    },
]