import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { Reacher } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]