import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { Reacher } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1gb3VJ8_OX4-n44I1LISzZQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1JHadLfFfLComrb4blNZ_Cw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1yXijIxyM6OgXhKElPeeTpg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1eF23WuWVJAqE6hzZweAzEg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1j3rUM-N-Mqpqkwz00TyjOg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1H2G0xoWA8N33sir9VMJXig',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1gpAxuVnLwl2oKhgKWpJMXA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Reacher',
        imageUrl: Reacher,
        verificationCode: verificationCode[37].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1Mo8mm5np64IumNoxVTcYog',
        youtubeLink: '',
        uploaded: true,
    },
]