import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { HelloMyGirl } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1std3TjO1WJ-tZTt_8xzRqQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1xZ-uuDe50T0sDfcODcbFxw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1jVKq98jcC-bHt1L1vOfXrQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1p2XmcGdrBtZULwBQBgLocw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/13PMeoJNi15U0oVHgI3VWvQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/10IPaoVzDu8rl03wLJK1P-A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1qbZUhb-8kUDWwtbcz29UYA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/18apXPBpHyM1F5IlheQD1FQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1u6B9rBFazC5KeI5krV7O7w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1Cml8AEYFMNtwiKuzEewdtg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1xpv4OIJUlWjQhRMIMRWLCA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/11BYsIO9UpcLvEPJdU8OAAw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/13bcnPpUwQKBvNmI5iOLq1g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1c0Lr4Y_RS5FsWz8w38ZbGg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1EMasxSaRoEcDxV2b1mvd-g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/11W4wh4mGn6DKX45BjBeFlw',
        youtubeLink: 'https://1024terabox.com/s/1O0N6jgakm8tPylTF_5gELA',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1-UP6gv2Yqa-ZnF3fKzsHog',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1yt3au_c050TLAKaiINpk7Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1QhxeL2H9KZ-v6-1HVzCOhA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1Rn02hDaM8WpNNNmWa5D5LQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1U81pS0M_6VahnODGNsH3ZA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1llPP7ef2OHNwNis5e6aTQg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1HIfw8MD9elh68W_FF7PjGQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Hello My Girl',
        imageUrl: HelloMyGirl,
        verificationCode: verificationCode[60].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1zxx8YWBWxlvuBPMK4AgZgA',
        youtubeLink: '',
        uploaded: false,
    },
]