import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { DanceOfTheSky } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ec2Tzoh0Hsz5CCPEJ_FD0w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/11TV6AnoP5tNJDvbW9J1wOg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/19wOkITyBXQ75YHmV654ZOw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1pxRhUZydBT1ODmgYxpdfLw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1C5YUMEv-lf9rNWnWWQo9Gg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1KFSnW_g1EN_ndKyje4uHdQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/17Fg7FME52msKS69BWbEmHA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1T8khyG5tMxDtrCSV4ORv-w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1RKWeRTMDl48KO5nXdERMSw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1wAcfe2BucvcZiv5Z4HJL8A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/17Vi20ffuX8w02DjciwXz2w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1e9vUxMpD1uAr7dtMg6Zn4g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1NjSCiuAQPQwiymy55y6fBQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/13yqRBNkHX8jOePInQq40kg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1CHsseBbQ_-5kKVlV1o4Rnw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/18r4uWNrOcVWHlGY5boIWqg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1n19b3yFr8O7AKWYypZW8mw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1s4abCUYJ-sOrf5-mrLBbBw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1dFtJ81EVAYdlEFR0rsULOw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1GpwRYlng2Nh5nbUgXn4jEw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/15wuYTz-Z3KdizRoOsR-oRA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/109UxY1x1FV650jwvfNGSXQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1QZcGudGEdqWKqZDfuu8lBg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1dA--OepmKryZv3NrRN4wrg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1qYcv2UNBGhf1QukADuUT5A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1qEQzoi2vBcAzESdQnV_dPw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1xv3JEy8piUXcJo2hK7ndNw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Dance Of The Sky',
        imageUrl: DanceOfTheSky,
        verificationCode: verificationCode[56].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1mYOLgagh1FcEsHEGIDzmoA',
        youtubeLink: '',
        uploaded: false,
    },
]