import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { SquidGameS1 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]