import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { SquidGameS1 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1THzx91MwKKPj6AX33sBcBg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1dcHwI4FyPTaAZZ_mdWzcOg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1DvEAbgY7sz_xZTP-izjHqg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1meSZ3jFl1kaEkLF6n9PuTQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1XcoGLpL4TV8-XATOFe9zgQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1PeqwaLyn72WYJRaPI1i_UA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1aPXSyceBw9rHfG6FtLAR8w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/196m9pcB49p1q804otWJo_g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Squid Game Seasong 1',
        imageUrl: SquidGameS1,
        verificationCode: verificationCode[38].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1pZEYSJvU_doviH7MkUcrUg',
        youtubeLink: '',
        uploaded: true,
    },
]