import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { School2017 } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: 'https://1024terabox.com/s/1N1_roFI-JPkhMugEyWFgVA',
        uploaded: true,
    },
    {
        id: 2,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1hSvWsxZPSjvinD9MFZAg4Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1fOto-ul6XB33O8mnyV1AHg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/15BTG6eEJ2rYtDJoXZcfoqA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1rY48psxf_EdreyCXUmPVmw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1NdNkCnmBZDkRbzsYm3od-Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'School 2017',
        imageUrl: School2017,
        verificationCode: verificationCode[21].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]
