import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { Goblin } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1uXt41eNW-5mQFRHyM6vLcA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1LiJFMfBZwR6ZrsR0I9-3PA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/14YZjhhwnRKXOptaJojdMRA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1dPVKdQlH77CW-RPxo-6Z5g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1gNFvtTp_MvCAD9fcv9oRVQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1rt3kfykhOZkVKFzv3ROKwg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1G9_TnYKFDoYHSL9XHijJIQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1kFvwu_fDhx2EdPQhduSIhw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1CCo_UoUqRUnULfgI19Uyfw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/11ZZ6Tuy-LIWjyBPQGaX1NQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1kjsIE6RIL62LyLILzch5DA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1TohWN__1wgSYWYFJzkRufA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1ICsqS6xwknEFweHHWE5nCw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1-MtdU0PiZy7jY7mCP1o9Xw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1rVQJ2pCw-vFR_x9kaNG9Ag',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Goblin',
        imageUrl: Goblin,
        verificationCode: verificationCode[9].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1PioukpRU7hifW4CkMYKiQg',
        youtubeLink: '',
        uploaded: true,
    },
]