import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { DalliAndCockyPrince } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1C5J9aCFldtNziVfKQurpvg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1-wGiO0XlTaVD5vfQhJKPWw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/18R3dTjE8-0IMoSBb68sGQg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1uf6sWPTwyFoEItQdi4rAzQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1HjEZgR7XqDJBh1JqJtyGlQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1HW1HB_N6ujovadsc1AIAeg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1BAAPlLdctSNnfdDDQ5sq1g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1p_kBHsNYGToYChAJzFbM0A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/10_7PM3Ojw1_g9iNxiw3oyA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1612goNyXphPe-ofReeW5HA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1srywcOt21ghF_OnyIyd6yA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1Az1JdcL-ngbrvZZnFYEOZQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1306z9qxF_IeUcc_iVjybyw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1khwpEmWNZF3jIwIhoYn6Bg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/12jZ3pSp28lLOWDlCnY6erg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Dali And Cocky Prince',
        imageUrl: DalliAndCockyPrince,
        verificationCode: verificationCode[55].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1hZoKCAFbmbPtOnH3bjOH5A',
        youtubeLink: '',
        uploaded: false,
    },
]