import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { IKnowILoveYou } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: 'https://youtu.be/JwrnjxkolcA?si=_R5j87Vd1h03V5Xr',
        uploaded: false,
    },
    {
        id: 2,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]