import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { IKnowILoveYou } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1mKmNuPz5lss1NZcQNeDDLw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1eD9x3DEPhsl0WURjMOeLQA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/15rVcIXrEz5VyXt_QUGc2Eg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1ItQYRPp2eDRrxmHDdIURJg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1ogTFH5RhkdTGqJN2O8Xw2A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/11reyWKXqXxW51XKPvXfl1Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1rnB4flPp6q6x_gJ07SI0hg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'I Know I Love You',
        imageUrl: IKnowILoveYou,
        verificationCode: verificationCode[34].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]