import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import {SweetFirstLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1y3kbyV3nQQiT3VuqkjkVCQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Sweet First Love',
        imageUrl: SweetFirstLove,
        verificationCode: verificationCode[42].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]