import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { BigMouth } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1N4CjXnqSSKl_MV0S3nIsWA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1ydKymKeOxeNepJFtB10XpQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/13x4PmvEFz9TeBOKkytvI4A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1GAyWV9NFwoH34nrXBbvVsg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1GNkZSfOLnkxesU0UQIL9wg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1jvN2apTAUCzxvphNww_45A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1NoDmRe7HtF901QAccIdNgA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1bP2i405sGdBlPHoNFP2rdw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1MCDwhnd_t8mqXy4DM7mkDQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1ahfumZvHbWJU_lnaWZgwVg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/17we850BD0QK2BtIqnvL3Qw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1X20BJlDmADf9Ns0C9Fb3WA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Big Mouth',
        imageUrl: BigMouth,
        verificationCode: verificationCode[26].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]