import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { LoveIsSweet } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1brjv8_fg8wRcmUCb2LvPfQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1TH-kcQnMA1QadOBaCr7rtg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1DVHALfoRPYGn3jq7eQ_04w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/14BMKpRXJNodMb4TXbOQo4Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1PjZuPu98r7iqoAiCzl6wRA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1Zda8Z9cMHKxFYHNaydA0rQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1-pph4FYMfMBvExWfAlAVRw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1e-qBQHmauI3jRQcPPa6Tgg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1zQV-yEf4pNUlt8lAkgvP-Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1rU1DwnTzMqTHUbplkuCuzw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1duW_XfJ58RIwcx0Ha20J_Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1FY0gg4eDUQ9XCsH72Vl_wQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/18kx8nuO6KSrnqiMI59FXUQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1gaIuZxAysLr3TGu6qp9cwg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ke--p1zQ2aMoqnw4LGCicQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1BN07dgeUXiXKdzqmEB1bgQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1yy9apNmIcSblpm6sAB-1CA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1Tl9wzzFUVISoklCFEMTBCA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1IJR-jRSm9oCZHbZX9SbluQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1eWfIg0AWbDJNseOEx7aYOA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1ivDfyvP1gH4k4AnNjeiREQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1a1icKtZKMaiQzNniAjUG8A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1fehW9_t2HxEbVdMxKRzuZw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1gEjOwjyiz60JNkKJLpnuQA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1fDXpLHg5ha1Vu8WQnHOBTQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/14lPqqEvBks4AAL8Z-jGSXg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1BHXe8UhLFjxnCs3_WpD0JQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1zk4Ik7Bw9fuiUbDYbZtfHg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 29,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1UR97TYScbWErxIp6Xsli4Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 30,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/16g_CGRYs0-07S8anJNUXCA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 31,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[30].verificationCode,
        videolink: 'https://1024terabox.com/s/1VXo19yuamfRvMW_lWEXZOQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 32,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[31].verificationCode,
        videolink: 'https://1024terabox.com/s/1XQ39_1ZfUpkTQEQ0Jj5fAQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 33,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[32].verificationCode,
        videolink: 'https://1024terabox.com/s/1cPb0rfv3fAJjfn_zmINxCg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 34,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[33].verificationCode,
        videolink: 'https://1024terabox.com/s/1Eq8HToSr-qWR0EUcYzzAKA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 35,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[34].verificationCode,
        videolink: 'https://1024terabox.com/s/1lJqd0IGP0ga6NrXSMdIX0g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 36,
        title: 'Love Is Sweet',
        imageUrl: LoveIsSweet,
        verificationCode: verificationCode[1].episodes[35].verificationCode,
        videolink: 'https://1024terabox.com/s/1V7A-QyT8RXOv1C66HiEh_Q',
        youtubeLink: '',
        uploaded: true,
    },
]