import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { ComeAndHugMe } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/10q9DnCSG2ikBYM2mWrXhYQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1XiJWIJ9zJhxfsd-M-ytEmQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1_oU2NrRdv6ciPoUpKvd_Vg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ui4epLQceT6hRZf0fUOanQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1HK-g8SQncrdXU5MKhmHm5Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1Tp1qSPammhiGlzB1gVBntg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1UQzRk-No1-4YLCPlMNU0Fw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1bC6uVJ7qTH6Zg1nwF3z_0Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1i3vePj66KA_N79-of5-4NQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1KL-1CzQrM23mwvIIa_tfwQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1orBddiIcuIAR_y4vEj1g2g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1gh7hnGOFn2iWkoz3txkmaw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1TSqpNLQ6zNLkeiVafPyy9Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1toI79zMnOnQjlGAqdw70Kg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1DF1Czx3WQVKebD3Lrz4QZQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Come And Hug Me',
        imageUrl: ComeAndHugMe,
        verificationCode: verificationCode[54].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1t55mhmE4Z1C-rFGyc71O_w',
        youtubeLink: '',
        uploaded: false,
    },
]