import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { FallInLove } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1dmMHLGiSNnY0-b8sP0Mlpg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1yOMWk3gG7EUBTrzvCQ_vOQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1rYgKPRZbiZyUo71O0XxJ7Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1WEba-z9Ml-rXVMVUt0iuRg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1wG6dXRvGVvfts2GRUhyC8g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1YJTJkpVf2eLFUiTjKygG5Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1EK80oHBCRWzIdSZ5GWXQWw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1cFamCkHvJnMLm0QsP61blQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1aLNZd1LlUoB0MYVUugizmA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1I7yRSJc3uHiOqIkIWmmQEQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1rX9bQtaIadvoDsVUumBQ6g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1nN7iNTPyiAZW2H_GZe8_tQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1Mzhv8QeHfnPN27x-pS4AqQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1-vUcwI8_cPsLAbCXYKZy0A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/18bZ2CpnIRPSpTJDSJd_rmQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/11kdo1JVrN61K0COVlJPUfA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1QVgc3z9c_tWcomO4AtK-YA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1zW91E5pJHicrE-jpNFcRVg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1eboOnMOPmSx4rYs3a9y2Ng',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1lM_pJ9MWSVohQB-w0eherQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1rOD6W9Gn4my-_JSr14rCvw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/154zdKm1e6WJrdtStV23uuQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1MoZ6JCJtRqvrAE79AqJk9A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1ue9o6DI3yFMJ4M5iBZ78Wg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: verificationCode[26].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1SBlzkEe3-WBgtFFs40RtLQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 33,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 34,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 35,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 36,
        title: 'Fall In Love',
        imageUrl: FallInLove,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]