import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { BestLover } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1GyD9EYX1AFyQgpxrs2hbzw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/12m530xyjyDmIENwrFi3H5g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1xAMvbAOOl6Uf6NvOk3mT0Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1j67KRrG9A1O_FU-vyzLMSw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/11GlD_mrJWREXE50DlRqozw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1vGBev-S5blnBib5i0EMD8Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1Hk3RAmQSjcCF2pEX7u4qlw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1K6Efd83vWy9c_DCF2jtbwg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1sasWWqHuRW_K-QuGellWPw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1wOg8_yVzucBbY022MDtg6g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ztyladk7fyZbs3AW0OHoHg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1H8zOa97n745-CGrTqx7vcA',
        youtubeLink: '',
        uploaded: true,
    },
]