import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { BestLover } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Best Lover',
        imageUrl: BestLover,
        verificationCode: verificationCode[51].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]