import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { MyGirlFriendIsAnAlien } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1EG0LQGgdFJNX0rgRJd4n4w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1zXnj3Xxmx4DvO2TzCU3kIA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1GbXqQLs40-imB0f77HXMkg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1R76bNsXus_EpcShgXeBgCQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1xWtQc3eJ5WUSiw9kYPUP5Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1zqtxbQ8CP4cT0VBnAPxMVg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1oI46kk_x52U8p9dRO1sNRw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1E6W8nkzzC8YCzxNiTUJleg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/12YfMpBMS8bZTaZukFEDTKQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1VeVHbVG6aKSYf9F6XZLPsA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1BPhqRxMmXpTUWgtBf8CTYQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1p8-f2vOmLJNdJq9NCP2Y4g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1ifHdpioZ9u0dlT_OT5sqpQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1CoGzwdHnZopL9SgqhlgrUA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1U4VcPApjxvD7qlgl5um9xg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/14krsp2lipaTL_TX2ZmQpgw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1eedhVO5wgeK1LZErKYoohA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1Cmz58AXsqApnP1E1UKWADw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1LxvaQS3SR_SSAtYI-02a5w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1fBaYU7a5WBcJKwk-AIalBg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1RNFakYCYJmUEe89PMatERA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1gHsROcwhosd7xlLqQg8fOg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/19OnJkYAiyFgp_W84C5Ytow',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1gpQtJTkUfGbu6vd0UfJnnw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/17CdcNOHWd2ACAHeF0c1laQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1enUn69spR4sfEkRf75eviA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1k6kguo9DJUqitElzlHFsgA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'My Girl Friend Is An Alien',
        imageUrl: MyGirlFriendIsAnAlien,
        verificationCode: verificationCode[17].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1nu0XNHnM_Vqk9bd-Qieeqg',
        youtubeLink: '',
        uploaded: true,
    },
]