import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { DatingInTheKitchen } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1GISBeH_wixLcredChvNceg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1kISyfarHwJEKvY5I7SuI6A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1TdvubXAkeIC-wuGWz5CMyQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1AEvWQMMMcBt7gnOvIU5Y_g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1eCRawFfCRXlD8VVf5CP8PQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1Aap7v-C4Pghn0BAJ9n-vbg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1w4_rntX_cJ35vqZKavy96Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1MHZapoGNjY0CNCR-RiIIOQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1dT2x_4g1hUyvvsqb5Pvymw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1kTzXGXc1jbupKkBZOQn07w',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1GN6zReiIOfHzWFWnLLhWuA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/16bjVwWbDfMzvLDf-lZ88Tw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1uVixWs8J090ofQ-CINMBAQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1p8C6Q5WA9R7fT2tKDUpI8A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1hUL4P7_Nheg1DuBim_n9DA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZxdFUz6RfLZBQuQLG9cnmg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1aySDnc2bXiiC9mK9W8p2pg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1WRbsAsyDx8_hD-Uq1C5ksQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/17J-z7lbN7udOt_gJGtQl1Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1obOfi1oMoBu8UKKN0B8QCQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1YtVy0q45L3lnpQDrBH2lig',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/17GREACTH-QSVD65sJyxQOw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1gLZNcr63NP9IFq3lcabSdQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1wrQQj-xVRsJqeZZWialD6Q',
        youtubeLink: '',
        uploaded: true,
    },
]