import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { DatingInTheKitchen } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1GISBeH_wixLcredChvNceg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1kISyfarHwJEKvY5I7SuI6A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1TdvubXAkeIC-wuGWz5CMyQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1AEvWQMMMcBt7gnOvIU5Y_g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Dating In The Kitchen',
        imageUrl: DatingInTheKitchen,
        verificationCode: verificationCode[28].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]