import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { GenZ } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1v3FACXxSNhA2B-hYMdfBSQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1ficxt798TufOKNijz5SmXw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[24].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[25].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[26].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[27].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[28].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[29].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[30].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[31].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 33,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[32].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 34,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[33].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 35,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[34].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 36,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[35].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 37,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[36].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 38,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[37].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 39,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[38].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 40,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[39].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]