import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { GenZ } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1v3FACXxSNhA2B-hYMdfBSQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1ficxt798TufOKNijz5SmXw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1cW5I9S_qN5UrSXDLllxRDg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1gsh27x7LKojYvv2rB7a1OQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1g_0gZaV5Fhkujgm5z5apIg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1tk1Z5O8ETt1nleKNK0L5kA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1ttc84hiVnuWkUS5QHq-2Ew',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1JCXieOn8p_AQI8iLrqw0ug',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1_xZaxEMZI3NkZBSrOZjedg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1MrVePXde-uxw0Ijn9z_zEA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1J5OFdWiJHNH7CDPwiP7oHA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/18HrlNgA5JH0rouyS8SJ35Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1V0pM95631PcRZIOQXezrtg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1U-MT3XWlH-gRpHRHjKHaIQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1pPpsqbawhJzULAuhaNoAlQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1Tpgn2metLLuNNnbPCVb6Fw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1MWpxQjRGxiYuLCVn3L53YQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1X0J2R5iy0fgXj-KEqhP6uA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1GfOcOElIF9R5c_-YYQ3kHA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1HBmvqUZcjkntU8aJ_6bWdA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1iOR9yTiV073Kz0exVBIyNA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[24].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[25].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[26].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[27].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[28].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[29].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 31,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[30].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 32,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[31].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 33,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[32].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 34,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[33].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 35,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[34].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 36,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[35].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 37,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[36].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 38,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[37].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 39,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[38].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 40,
        title: 'Gen Z',
        imageUrl: GenZ,
        verificationCode: verificationCode[30].episodes[39].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]