import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { UnlockMyBoss } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1r15c-QiozmsoKzbk3KG3Yg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1ZGtYHpu4iwvCH2raSvD_vA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1BxmxMn1c5mLeMRuGbF1syQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1Tv8Cd4J2Zmqj_4Bj3KXf5g',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1QUTV55-rZ-uYCxgWrUI4nQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1qiSdRlGxHuCmz9qOhe-GPQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1J5TZ9XMbpUG6m-QPT_PxmQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/16zOUUR0BqbUyb55InB7udA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1KXvNvDf1kyDgjEfuo3qGzQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1c5KPXLdjJIeCrhm55dNuxg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1WgxqCI1-N5WkeWANWMVaBQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1Qd8CwIEPIaCTXx8HjKQqiQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1A4R8mFdGhKijkePa9o88yw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1Mwgfgqs9oo__6f8Q8Zw1hA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1X4A_TIzsX9ESsfe3Ujvi9Q',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1RDjz5tdcJDSSkKAYM1Olog',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1UM1NBXZMo9zrGjcWpkQ0oA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1gAhOZHfD6-dEIsbWlACsgQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1t3GlBftafoVNPSoAZLdq9w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1p2wa4W6sICHXpleZ8bEqTw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1XCBCtccYV40-hoiMtExJ2A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ge66QSm9HNDxbHWFKPTlLg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1xMt7fSAunC9WjO7JSYJTxQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Unlock My Boss',
        imageUrl: UnlockMyBoss,
        verificationCode: verificationCode[46].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1II9uNBygNNS53eQTWqJuPA',
        youtubeLink: '',
        uploaded: false,
    },
]