import { TheLoveYouGaveMe } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'TheLoveYouGaveMe',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: '',
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]