import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { TheLoveYouGaveMe } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1M5SCHB2k4yao8KtNl5nxFQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1I70idE23aSPwjyw6RX96VQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1GXGuB0DnLDxytUklbwrerQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/13PTEXVgDg77g_qW955ZG8A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/15KVeNiuSH4QpB7RdqVBsTA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1Ec25peVlxJeuDqy6vxQZXw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1fRMZCrMmAOia35jbRFscbg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 8,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/1WurX4eSZ_9e1YVSU9wb4_Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 9,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1sRJ-lIJrJB4rjkQZ6L8FEA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 10,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1hhLhjgX9zZflF5wnoY2tOQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 11,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1QOKRAiNY9f5x-ItxYDFBng',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 12,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/1A1nbvHT1u0PfPGkfmVj96Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 13,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1bfu3A81EHQpMP1EDNiDu4A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 14,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1_Mp-vRQ7xB-dVCa1sYd0Bg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 15,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1-AInFMwZ8Bx2SMqXTMJRyw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 16,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1ejG7ic3ubA2cYUiS59HYfQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 17,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1gr0rKkMPoH2Tm7YLOhejiA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 18,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1qlEuKT64q9Xu4dqHqo9Fug',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 19,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1bYrw-7kIjrEPP_RulGMJwg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 20,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1UId_RV--GXaCXZwGeQgpcQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 21,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/13W_fttyns-zeZC6jzJnksw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 22,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1LJAKIJIUlzu-eCGtlMcJFA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 23,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1SB7yBOQ2pn_oXXfy7aBcjg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 24,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/1Z6ummo2wKt5EpaXMKCuTIQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 25,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/1xvXgqLlHiBb4lGUrPLddBQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 26,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1vc7B6hDkawLMDmgTTbVtMA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 27,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1asgsWkOHkmB6IJD5uj06-Q',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 28,
        title: 'The Love You Gave Me',
        imageUrl: TheLoveYouGaveMe,
        verificationCode: verificationCode[23].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1VzXtYj_97gsh1R6WlaBlSw',
        youtubeLink: '',
        uploaded: true,
    },
]