import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { SquidGameS2} from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: 'https://youtu.be/JwrnjxkolcA?si=_R5j87Vd1h03V5Xr',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]