import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { SquidGameS2} from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/13e8OQlN0R74oAE-niC_cmQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1-G52OY54Dj0VcwCFJ8lsIQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1H5cCjff6jF_2sTby-YuUEQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1bSZ-NsbgMEvzhccOWEL0Zw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/12UlfxyyZtcVcPhk2CrTvpQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1zWBTupyB59hiMMG-6byH2g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Squid Game Season 2',
        imageUrl: SquidGameS2,
        verificationCode: verificationCode[39].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1mTRIz7p7lCvDZsh3hOMjaQ',
        youtubeLink: '',
        uploaded: true,
    },
]