import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { Gyeongseong } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/142nCbSS6STtQA6dk0U4mxA',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1pIF9MsAxe1iRX_Jp6-VQbQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1XoZ96rA0Z9o1vS0JJcJF8g',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/1itdVuK6Kid0AeWpfuWmkeg',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 5,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1PKYDMTiOjF_d2PqyZzD5XQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 6,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1Dz2zs9lnVCRpyxMOI4yvNw',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 7,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1CZ-cQTD0E3JL7zOBWHZkRw',
        youtubeLink: '',
        uploaded: true,
    },
]