import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { Gyeongseong } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[0].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[1].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[2].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Gyeongseong',
        imageUrl: Gyeongseong,
        verificationCode: verificationCode[32].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]