import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { LoveAtNight } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1nV9Fx7XOo0G8foCwdRA3mQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 2,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1UsvC6ADY-8CYX7qaaFWUAQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 3,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1q4go4HxxrfjGarqjZiBsOw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 4,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[3].verificationCode,
        videolink: 'https://1024terabox.com/s/122wmynINrSJM-kiqw_W8yg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[4].verificationCode,
        videolink: 'https://1024terabox.com/s/1PwOrx49MejDERZn3EwiJdA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[5].verificationCode,
        videolink: 'https://1024terabox.com/s/1J5epC4eCV7b-39BwrjLcMw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[6].verificationCode,
        videolink: 'https://1024terabox.com/s/1qQ2ZY7C-uJSaxs9MxrzZpw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[7].verificationCode,
        videolink: 'https://1024terabox.com/s/16KVe5kIKjY2Yol8wCsZNyQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[8].verificationCode,
        videolink: 'https://1024terabox.com/s/1hLKWuscg9x2cLx_ISmdvoA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[9].verificationCode,
        videolink: 'https://1024terabox.com/s/1quFczhnkYJE9EIHiJoPwfA',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[10].verificationCode,
        videolink: 'https://1024terabox.com/s/1SxkdVLT7GTCLDxisItGYiQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[11].verificationCode,
        videolink: 'https://1024terabox.com/s/15_1do7cZsfqgmzDwfEav8w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[12].verificationCode,
        videolink: 'https://1024terabox.com/s/1FP3ZzzFv1ARPw-wLqhm4Dw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[13].verificationCode,
        videolink: 'https://1024terabox.com/s/1obl_KJAyy63POhsqocFyKQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[14].verificationCode,
        videolink: 'https://1024terabox.com/s/1bxaz_wXABLzcjmPgtKJ46A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[15].verificationCode,
        videolink: 'https://1024terabox.com/s/1BwLX6ghY7e2cgokCB7ZWPw',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[16].verificationCode,
        videolink: 'https://1024terabox.com/s/1RGjWoPPotNdCEtSYuoSxTQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[17].verificationCode,
        videolink: 'https://1024terabox.com/s/1HdY2CyWmvWsddYSwJPUD2w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[18].verificationCode,
        videolink: 'https://1024terabox.com/s/1NHq9iGCQI_uZKWaq71GCZg',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[19].verificationCode,
        videolink: 'https://1024terabox.com/s/1bBeWx3N_sb6MzE9mDjQa1w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[20].verificationCode,
        videolink: 'https://1024terabox.com/s/1j2Lomzkre8gI76qHiN72ZQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[21].verificationCode,
        videolink: 'https://1024terabox.com/s/1YH1CxcsmblKB8kQ2OxgJjQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[22].verificationCode,
        videolink: 'https://1024terabox.com/s/1EvCd7pGK-REJ7s5A9VXx-w',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[23].verificationCode,
        videolink: 'https://1024terabox.com/s/19J7zMvIdAhTmZ2asNy1f-A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 25,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[24].verificationCode,
        videolink: 'https://1024terabox.com/s/182gosvS3soWoi9o2wuD54A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 26,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[25].verificationCode,
        videolink: 'https://1024terabox.com/s/1Yaizhu6Hea2-QdTkVV_S4A',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 27,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[26].verificationCode,
        videolink: 'https://1024terabox.com/s/1ABJGSDzmZVZ83BdIzINKsQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 28,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[27].verificationCode,
        videolink: 'https://1024terabox.com/s/1irknRovSFyYMTcnEnYmLZQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 29,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[28].verificationCode,
        videolink: 'https://1024terabox.com/s/1hpuHcW7u3JJvFxA18hxcKQ',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 30,
        title: 'Love At Night',
        imageUrl: LoveAtNight,
        verificationCode: verificationCode[64].episodes[29].verificationCode,
        videolink: 'https://1024terabox.com/s/1k_HowIABP66QQlaHj96anw',
        youtubeLink: '',
        uploaded: false,
    },
]