import { verificationCode } from "@/AllVerificationCode/VerificationCode"
import { LoveUnexpected } from "@assets"
export const Episodes = [
    {
        id: 1,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[0].verificationCode,
        videolink: 'https://1024terabox.com/s/1bfiIaExmV_uM02T2nrpzyQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 2,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[1].verificationCode,
        videolink: 'https://1024terabox.com/s/1BHTg85WarnMit_9BjrhP0A',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 3,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[2].verificationCode,
        videolink: 'https://1024terabox.com/s/1qBDWn90frVJ_KKNPb-seAQ',
        youtubeLink: '',
        uploaded: true,
    },
    {
        id: 4,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[3].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 5,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[4].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 6,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[5].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 7,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[6].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 8,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[7].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 9,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[8].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 10,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[9].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 11,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[10].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 12,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[11].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 13,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[12].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 14,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[13].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 15,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[14].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 16,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[15].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 17,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[16].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 18,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[17].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 19,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[18].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 20,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[19].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 21,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[20].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 22,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[21].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 23,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[22].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
    {
        id: 24,
        title: 'Love Unexpected',
        imageUrl: LoveUnexpected,
        verificationCode: verificationCode[35].episodes[23].verificationCode,
        videolink: '',
        youtubeLink: '',
        uploaded: false,
    },
]